package top.lover.hyperlink.entity;

import java.io.Serializable;
import java.util.Date;

public class CsAccessRateSet implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_access_rate_set.N_ID
     *
     * @mbggenerated
     */
    private Long nId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_access_rate_set.ACTIVATION_DAYS
     *
     * @mbggenerated
     */
    private Integer activationDays;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_access_rate_set.REGISTER_DAYS
     *
     * @mbggenerated
     */
    private Integer registerDays;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_access_rate_set.UNINSTALL_DAYS
     *
     * @mbggenerated
     */
    private Integer uninstallDays;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_access_rate_set.NODATA_HOURS
     *
     * @mbggenerated
     */
    private Integer nodataHours;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_access_rate_set.MONITOR_REGISTER_PUSH_HOURS
     *
     * @mbggenerated
     */
    private Integer monitorRegisterPushHours;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_access_rate_set.MONITOR_REGISTER_SMS_DAYS
     *
     * @mbggenerated
     */
    private Integer monitorRegisterSmsDays;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_access_rate_set.STR0
     *
     * @mbggenerated
     */
    private String str0;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_access_rate_set.STR1
     *
     * @mbggenerated
     */
    private String str1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_access_rate_set.COMP_ID
     *
     * @mbggenerated
     */
    private Long compId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_access_rate_set.CREATE_BY
     *
     * @mbggenerated
     */
    private Long createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_access_rate_set.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_access_rate_set.MODI_BY
     *
     * @mbggenerated
     */
    private Long modiBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_access_rate_set.MODI_TIME
     *
     * @mbggenerated
     */
    private Date modiTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_access_rate_set.ORG_ID
     *
     * @mbggenerated
     */
    private Long orgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_access_rate_set.SORT_NUM
     *
     * @mbggenerated
     */
    private Integer sortNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_access_rate_set.STATUS
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cs_access_rate_set
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_access_rate_set.N_ID
     *
     * @return the value of cs_access_rate_set.N_ID
     *
     * @mbggenerated
     */
    public Long getnId() {
        return nId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_access_rate_set.N_ID
     *
     * @param nId the value for cs_access_rate_set.N_ID
     *
     * @mbggenerated
     */
    public void setnId(Long nId) {
        this.nId = nId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_access_rate_set.ACTIVATION_DAYS
     *
     * @return the value of cs_access_rate_set.ACTIVATION_DAYS
     *
     * @mbggenerated
     */
    public Integer getActivationDays() {
        return activationDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_access_rate_set.ACTIVATION_DAYS
     *
     * @param activationDays the value for cs_access_rate_set.ACTIVATION_DAYS
     *
     * @mbggenerated
     */
    public void setActivationDays(Integer activationDays) {
        this.activationDays = activationDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_access_rate_set.REGISTER_DAYS
     *
     * @return the value of cs_access_rate_set.REGISTER_DAYS
     *
     * @mbggenerated
     */
    public Integer getRegisterDays() {
        return registerDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_access_rate_set.REGISTER_DAYS
     *
     * @param registerDays the value for cs_access_rate_set.REGISTER_DAYS
     *
     * @mbggenerated
     */
    public void setRegisterDays(Integer registerDays) {
        this.registerDays = registerDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_access_rate_set.UNINSTALL_DAYS
     *
     * @return the value of cs_access_rate_set.UNINSTALL_DAYS
     *
     * @mbggenerated
     */
    public Integer getUninstallDays() {
        return uninstallDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_access_rate_set.UNINSTALL_DAYS
     *
     * @param uninstallDays the value for cs_access_rate_set.UNINSTALL_DAYS
     *
     * @mbggenerated
     */
    public void setUninstallDays(Integer uninstallDays) {
        this.uninstallDays = uninstallDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_access_rate_set.NODATA_HOURS
     *
     * @return the value of cs_access_rate_set.NODATA_HOURS
     *
     * @mbggenerated
     */
    public Integer getNodataHours() {
        return nodataHours;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_access_rate_set.NODATA_HOURS
     *
     * @param nodataHours the value for cs_access_rate_set.NODATA_HOURS
     *
     * @mbggenerated
     */
    public void setNodataHours(Integer nodataHours) {
        this.nodataHours = nodataHours;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_access_rate_set.MONITOR_REGISTER_PUSH_HOURS
     *
     * @return the value of cs_access_rate_set.MONITOR_REGISTER_PUSH_HOURS
     *
     * @mbggenerated
     */
    public Integer getMonitorRegisterPushHours() {
        return monitorRegisterPushHours;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_access_rate_set.MONITOR_REGISTER_PUSH_HOURS
     *
     * @param monitorRegisterPushHours the value for cs_access_rate_set.MONITOR_REGISTER_PUSH_HOURS
     *
     * @mbggenerated
     */
    public void setMonitorRegisterPushHours(Integer monitorRegisterPushHours) {
        this.monitorRegisterPushHours = monitorRegisterPushHours;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_access_rate_set.MONITOR_REGISTER_SMS_DAYS
     *
     * @return the value of cs_access_rate_set.MONITOR_REGISTER_SMS_DAYS
     *
     * @mbggenerated
     */
    public Integer getMonitorRegisterSmsDays() {
        return monitorRegisterSmsDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_access_rate_set.MONITOR_REGISTER_SMS_DAYS
     *
     * @param monitorRegisterSmsDays the value for cs_access_rate_set.MONITOR_REGISTER_SMS_DAYS
     *
     * @mbggenerated
     */
    public void setMonitorRegisterSmsDays(Integer monitorRegisterSmsDays) {
        this.monitorRegisterSmsDays = monitorRegisterSmsDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_access_rate_set.STR0
     *
     * @return the value of cs_access_rate_set.STR0
     *
     * @mbggenerated
     */
    public String getStr0() {
        return str0;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_access_rate_set.STR0
     *
     * @param str0 the value for cs_access_rate_set.STR0
     *
     * @mbggenerated
     */
    public void setStr0(String str0) {
        this.str0 = str0 == null ? null : str0.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_access_rate_set.STR1
     *
     * @return the value of cs_access_rate_set.STR1
     *
     * @mbggenerated
     */
    public String getStr1() {
        return str1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_access_rate_set.STR1
     *
     * @param str1 the value for cs_access_rate_set.STR1
     *
     * @mbggenerated
     */
    public void setStr1(String str1) {
        this.str1 = str1 == null ? null : str1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_access_rate_set.COMP_ID
     *
     * @return the value of cs_access_rate_set.COMP_ID
     *
     * @mbggenerated
     */
    public Long getCompId() {
        return compId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_access_rate_set.COMP_ID
     *
     * @param compId the value for cs_access_rate_set.COMP_ID
     *
     * @mbggenerated
     */
    public void setCompId(Long compId) {
        this.compId = compId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_access_rate_set.CREATE_BY
     *
     * @return the value of cs_access_rate_set.CREATE_BY
     *
     * @mbggenerated
     */
    public Long getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_access_rate_set.CREATE_BY
     *
     * @param createBy the value for cs_access_rate_set.CREATE_BY
     *
     * @mbggenerated
     */
    public void setCreateBy(Long createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_access_rate_set.CREATE_TIME
     *
     * @return the value of cs_access_rate_set.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_access_rate_set.CREATE_TIME
     *
     * @param createTime the value for cs_access_rate_set.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_access_rate_set.MODI_BY
     *
     * @return the value of cs_access_rate_set.MODI_BY
     *
     * @mbggenerated
     */
    public Long getModiBy() {
        return modiBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_access_rate_set.MODI_BY
     *
     * @param modiBy the value for cs_access_rate_set.MODI_BY
     *
     * @mbggenerated
     */
    public void setModiBy(Long modiBy) {
        this.modiBy = modiBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_access_rate_set.MODI_TIME
     *
     * @return the value of cs_access_rate_set.MODI_TIME
     *
     * @mbggenerated
     */
    public Date getModiTime() {
        return modiTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_access_rate_set.MODI_TIME
     *
     * @param modiTime the value for cs_access_rate_set.MODI_TIME
     *
     * @mbggenerated
     */
    public void setModiTime(Date modiTime) {
        this.modiTime = modiTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_access_rate_set.ORG_ID
     *
     * @return the value of cs_access_rate_set.ORG_ID
     *
     * @mbggenerated
     */
    public Long getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_access_rate_set.ORG_ID
     *
     * @param orgId the value for cs_access_rate_set.ORG_ID
     *
     * @mbggenerated
     */
    public void setOrgId(Long orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_access_rate_set.SORT_NUM
     *
     * @return the value of cs_access_rate_set.SORT_NUM
     *
     * @mbggenerated
     */
    public Integer getSortNum() {
        return sortNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_access_rate_set.SORT_NUM
     *
     * @param sortNum the value for cs_access_rate_set.SORT_NUM
     *
     * @mbggenerated
     */
    public void setSortNum(Integer sortNum) {
        this.sortNum = sortNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_access_rate_set.STATUS
     *
     * @return the value of cs_access_rate_set.STATUS
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_access_rate_set.STATUS
     *
     * @param status the value for cs_access_rate_set.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_access_rate_set
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", nId=").append(nId);
        sb.append(", activationDays=").append(activationDays);
        sb.append(", registerDays=").append(registerDays);
        sb.append(", uninstallDays=").append(uninstallDays);
        sb.append(", nodataHours=").append(nodataHours);
        sb.append(", monitorRegisterPushHours=").append(monitorRegisterPushHours);
        sb.append(", monitorRegisterSmsDays=").append(monitorRegisterSmsDays);
        sb.append(", str0=").append(str0);
        sb.append(", str1=").append(str1);
        sb.append(", compId=").append(compId);
        sb.append(", createBy=").append(createBy);
        sb.append(", createTime=").append(createTime);
        sb.append(", modiBy=").append(modiBy);
        sb.append(", modiTime=").append(modiTime);
        sb.append(", orgId=").append(orgId);
        sb.append(", sortNum=").append(sortNum);
        sb.append(", status=").append(status);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}