package top.lover.hyperlink.entity;

import java.io.Serializable;
import java.util.Date;

public class CsDefaultTouchTime implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_default_touch_time.N_ID
     *
     * @mbggenerated
     */
    private Long nId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_default_touch_time.STR0
     *
     * @mbggenerated
     */
    private String str0;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_default_touch_time.STR1
     *
     * @mbggenerated
     */
    private String str1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_default_touch_time.COMP_ID
     *
     * @mbggenerated
     */
    private Long compId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_default_touch_time.CREATE_BY
     *
     * @mbggenerated
     */
    private Long createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_default_touch_time.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_default_touch_time.MODI_BY
     *
     * @mbggenerated
     */
    private Long modiBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_default_touch_time.MODI_TIME
     *
     * @mbggenerated
     */
    private Date modiTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_default_touch_time.ORG_ID
     *
     * @mbggenerated
     */
    private Long orgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_default_touch_time.SORT_NUM
     *
     * @mbggenerated
     */
    private Integer sortNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_default_touch_time.STATUS
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_default_touch_time.MSG_END_TIME
     *
     * @mbggenerated
     */
    private String msgEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_default_touch_time.MSG_START_TIME
     *
     * @mbggenerated
     */
    private String msgStartTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_default_touch_time.PUSH_END_TIME
     *
     * @mbggenerated
     */
    private String pushEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_default_touch_time.PUSH_START_TIME
     *
     * @mbggenerated
     */
    private String pushStartTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cs_default_touch_time
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_default_touch_time.N_ID
     *
     * @return the value of cs_default_touch_time.N_ID
     *
     * @mbggenerated
     */
    public Long getnId() {
        return nId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_default_touch_time.N_ID
     *
     * @param nId the value for cs_default_touch_time.N_ID
     *
     * @mbggenerated
     */
    public void setnId(Long nId) {
        this.nId = nId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_default_touch_time.STR0
     *
     * @return the value of cs_default_touch_time.STR0
     *
     * @mbggenerated
     */
    public String getStr0() {
        return str0;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_default_touch_time.STR0
     *
     * @param str0 the value for cs_default_touch_time.STR0
     *
     * @mbggenerated
     */
    public void setStr0(String str0) {
        this.str0 = str0 == null ? null : str0.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_default_touch_time.STR1
     *
     * @return the value of cs_default_touch_time.STR1
     *
     * @mbggenerated
     */
    public String getStr1() {
        return str1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_default_touch_time.STR1
     *
     * @param str1 the value for cs_default_touch_time.STR1
     *
     * @mbggenerated
     */
    public void setStr1(String str1) {
        this.str1 = str1 == null ? null : str1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_default_touch_time.COMP_ID
     *
     * @return the value of cs_default_touch_time.COMP_ID
     *
     * @mbggenerated
     */
    public Long getCompId() {
        return compId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_default_touch_time.COMP_ID
     *
     * @param compId the value for cs_default_touch_time.COMP_ID
     *
     * @mbggenerated
     */
    public void setCompId(Long compId) {
        this.compId = compId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_default_touch_time.CREATE_BY
     *
     * @return the value of cs_default_touch_time.CREATE_BY
     *
     * @mbggenerated
     */
    public Long getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_default_touch_time.CREATE_BY
     *
     * @param createBy the value for cs_default_touch_time.CREATE_BY
     *
     * @mbggenerated
     */
    public void setCreateBy(Long createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_default_touch_time.CREATE_TIME
     *
     * @return the value of cs_default_touch_time.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_default_touch_time.CREATE_TIME
     *
     * @param createTime the value for cs_default_touch_time.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_default_touch_time.MODI_BY
     *
     * @return the value of cs_default_touch_time.MODI_BY
     *
     * @mbggenerated
     */
    public Long getModiBy() {
        return modiBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_default_touch_time.MODI_BY
     *
     * @param modiBy the value for cs_default_touch_time.MODI_BY
     *
     * @mbggenerated
     */
    public void setModiBy(Long modiBy) {
        this.modiBy = modiBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_default_touch_time.MODI_TIME
     *
     * @return the value of cs_default_touch_time.MODI_TIME
     *
     * @mbggenerated
     */
    public Date getModiTime() {
        return modiTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_default_touch_time.MODI_TIME
     *
     * @param modiTime the value for cs_default_touch_time.MODI_TIME
     *
     * @mbggenerated
     */
    public void setModiTime(Date modiTime) {
        this.modiTime = modiTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_default_touch_time.ORG_ID
     *
     * @return the value of cs_default_touch_time.ORG_ID
     *
     * @mbggenerated
     */
    public Long getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_default_touch_time.ORG_ID
     *
     * @param orgId the value for cs_default_touch_time.ORG_ID
     *
     * @mbggenerated
     */
    public void setOrgId(Long orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_default_touch_time.SORT_NUM
     *
     * @return the value of cs_default_touch_time.SORT_NUM
     *
     * @mbggenerated
     */
    public Integer getSortNum() {
        return sortNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_default_touch_time.SORT_NUM
     *
     * @param sortNum the value for cs_default_touch_time.SORT_NUM
     *
     * @mbggenerated
     */
    public void setSortNum(Integer sortNum) {
        this.sortNum = sortNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_default_touch_time.STATUS
     *
     * @return the value of cs_default_touch_time.STATUS
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_default_touch_time.STATUS
     *
     * @param status the value for cs_default_touch_time.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_default_touch_time.MSG_END_TIME
     *
     * @return the value of cs_default_touch_time.MSG_END_TIME
     *
     * @mbggenerated
     */
    public String getMsgEndTime() {
        return msgEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_default_touch_time.MSG_END_TIME
     *
     * @param msgEndTime the value for cs_default_touch_time.MSG_END_TIME
     *
     * @mbggenerated
     */
    public void setMsgEndTime(String msgEndTime) {
        this.msgEndTime = msgEndTime == null ? null : msgEndTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_default_touch_time.MSG_START_TIME
     *
     * @return the value of cs_default_touch_time.MSG_START_TIME
     *
     * @mbggenerated
     */
    public String getMsgStartTime() {
        return msgStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_default_touch_time.MSG_START_TIME
     *
     * @param msgStartTime the value for cs_default_touch_time.MSG_START_TIME
     *
     * @mbggenerated
     */
    public void setMsgStartTime(String msgStartTime) {
        this.msgStartTime = msgStartTime == null ? null : msgStartTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_default_touch_time.PUSH_END_TIME
     *
     * @return the value of cs_default_touch_time.PUSH_END_TIME
     *
     * @mbggenerated
     */
    public String getPushEndTime() {
        return pushEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_default_touch_time.PUSH_END_TIME
     *
     * @param pushEndTime the value for cs_default_touch_time.PUSH_END_TIME
     *
     * @mbggenerated
     */
    public void setPushEndTime(String pushEndTime) {
        this.pushEndTime = pushEndTime == null ? null : pushEndTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_default_touch_time.PUSH_START_TIME
     *
     * @return the value of cs_default_touch_time.PUSH_START_TIME
     *
     * @mbggenerated
     */
    public String getPushStartTime() {
        return pushStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_default_touch_time.PUSH_START_TIME
     *
     * @param pushStartTime the value for cs_default_touch_time.PUSH_START_TIME
     *
     * @mbggenerated
     */
    public void setPushStartTime(String pushStartTime) {
        this.pushStartTime = pushStartTime == null ? null : pushStartTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_default_touch_time
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", nId=").append(nId);
        sb.append(", str0=").append(str0);
        sb.append(", str1=").append(str1);
        sb.append(", compId=").append(compId);
        sb.append(", createBy=").append(createBy);
        sb.append(", createTime=").append(createTime);
        sb.append(", modiBy=").append(modiBy);
        sb.append(", modiTime=").append(modiTime);
        sb.append(", orgId=").append(orgId);
        sb.append(", sortNum=").append(sortNum);
        sb.append(", status=").append(status);
        sb.append(", msgEndTime=").append(msgEndTime);
        sb.append(", msgStartTime=").append(msgStartTime);
        sb.append(", pushEndTime=").append(pushEndTime);
        sb.append(", pushStartTime=").append(pushStartTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}