package top.lover.hyperlink.entity;

import java.io.Serializable;
import java.util.Date;

public class CsDefaultTouchRate implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_default_touch_rate.N_ID
     *
     * @mbggenerated
     */
    private Long nId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_default_touch_rate.STR0
     *
     * @mbggenerated
     */
    private String str0;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_default_touch_rate.STR1
     *
     * @mbggenerated
     */
    private String str1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_default_touch_rate.COMP_ID
     *
     * @mbggenerated
     */
    private Long compId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_default_touch_rate.CREATE_BY
     *
     * @mbggenerated
     */
    private Long createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_default_touch_rate.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_default_touch_rate.MODI_BY
     *
     * @mbggenerated
     */
    private Long modiBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_default_touch_rate.MODI_TIME
     *
     * @mbggenerated
     */
    private Date modiTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_default_touch_rate.ORG_ID
     *
     * @mbggenerated
     */
    private Long orgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_default_touch_rate.SORT_NUM
     *
     * @mbggenerated
     */
    private Integer sortNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_default_touch_rate.STATUS
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_default_touch_rate.MSG_STATUS_TIME
     *
     * @mbggenerated
     */
    private Long msgStatusTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_default_touch_rate.MSG_STATUS_TIME_TYPE
     *
     * @mbggenerated
     */
    private Integer msgStatusTimeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_default_touch_rate.MSG_UNLOAD_TIME
     *
     * @mbggenerated
     */
    private Long msgUnloadTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_default_touch_rate.MSG_UNLOAD_TIME_TYPE
     *
     * @mbggenerated
     */
    private Integer msgUnloadTimeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_default_touch_rate.PUSH_RESERV_INFO_TIME
     *
     * @mbggenerated
     */
    private Long pushReservInfoTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_default_touch_rate.PUSH_RESERV_INFO_TIME_TYPE
     *
     * @mbggenerated
     */
    private Integer pushReservInfoTimeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_default_touch_rate.PUSH_STATUS_TIME
     *
     * @mbggenerated
     */
    private Long pushStatusTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_default_touch_rate.PUSH_STATUS_TIME_TYPE
     *
     * @mbggenerated
     */
    private Integer pushStatusTimeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_default_touch_rate.PUSH_UN_REGISTER
     *
     * @mbggenerated
     */
    private Long pushUnRegister;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_default_touch_rate.PUSH_UN_REGISTER_TYPE
     *
     * @mbggenerated
     */
    private Integer pushUnRegisterType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cs_default_touch_rate
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_default_touch_rate.N_ID
     *
     * @return the value of cs_default_touch_rate.N_ID
     *
     * @mbggenerated
     */
    public Long getnId() {
        return nId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_default_touch_rate.N_ID
     *
     * @param nId the value for cs_default_touch_rate.N_ID
     *
     * @mbggenerated
     */
    public void setnId(Long nId) {
        this.nId = nId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_default_touch_rate.STR0
     *
     * @return the value of cs_default_touch_rate.STR0
     *
     * @mbggenerated
     */
    public String getStr0() {
        return str0;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_default_touch_rate.STR0
     *
     * @param str0 the value for cs_default_touch_rate.STR0
     *
     * @mbggenerated
     */
    public void setStr0(String str0) {
        this.str0 = str0 == null ? null : str0.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_default_touch_rate.STR1
     *
     * @return the value of cs_default_touch_rate.STR1
     *
     * @mbggenerated
     */
    public String getStr1() {
        return str1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_default_touch_rate.STR1
     *
     * @param str1 the value for cs_default_touch_rate.STR1
     *
     * @mbggenerated
     */
    public void setStr1(String str1) {
        this.str1 = str1 == null ? null : str1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_default_touch_rate.COMP_ID
     *
     * @return the value of cs_default_touch_rate.COMP_ID
     *
     * @mbggenerated
     */
    public Long getCompId() {
        return compId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_default_touch_rate.COMP_ID
     *
     * @param compId the value for cs_default_touch_rate.COMP_ID
     *
     * @mbggenerated
     */
    public void setCompId(Long compId) {
        this.compId = compId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_default_touch_rate.CREATE_BY
     *
     * @return the value of cs_default_touch_rate.CREATE_BY
     *
     * @mbggenerated
     */
    public Long getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_default_touch_rate.CREATE_BY
     *
     * @param createBy the value for cs_default_touch_rate.CREATE_BY
     *
     * @mbggenerated
     */
    public void setCreateBy(Long createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_default_touch_rate.CREATE_TIME
     *
     * @return the value of cs_default_touch_rate.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_default_touch_rate.CREATE_TIME
     *
     * @param createTime the value for cs_default_touch_rate.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_default_touch_rate.MODI_BY
     *
     * @return the value of cs_default_touch_rate.MODI_BY
     *
     * @mbggenerated
     */
    public Long getModiBy() {
        return modiBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_default_touch_rate.MODI_BY
     *
     * @param modiBy the value for cs_default_touch_rate.MODI_BY
     *
     * @mbggenerated
     */
    public void setModiBy(Long modiBy) {
        this.modiBy = modiBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_default_touch_rate.MODI_TIME
     *
     * @return the value of cs_default_touch_rate.MODI_TIME
     *
     * @mbggenerated
     */
    public Date getModiTime() {
        return modiTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_default_touch_rate.MODI_TIME
     *
     * @param modiTime the value for cs_default_touch_rate.MODI_TIME
     *
     * @mbggenerated
     */
    public void setModiTime(Date modiTime) {
        this.modiTime = modiTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_default_touch_rate.ORG_ID
     *
     * @return the value of cs_default_touch_rate.ORG_ID
     *
     * @mbggenerated
     */
    public Long getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_default_touch_rate.ORG_ID
     *
     * @param orgId the value for cs_default_touch_rate.ORG_ID
     *
     * @mbggenerated
     */
    public void setOrgId(Long orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_default_touch_rate.SORT_NUM
     *
     * @return the value of cs_default_touch_rate.SORT_NUM
     *
     * @mbggenerated
     */
    public Integer getSortNum() {
        return sortNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_default_touch_rate.SORT_NUM
     *
     * @param sortNum the value for cs_default_touch_rate.SORT_NUM
     *
     * @mbggenerated
     */
    public void setSortNum(Integer sortNum) {
        this.sortNum = sortNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_default_touch_rate.STATUS
     *
     * @return the value of cs_default_touch_rate.STATUS
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_default_touch_rate.STATUS
     *
     * @param status the value for cs_default_touch_rate.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_default_touch_rate.MSG_STATUS_TIME
     *
     * @return the value of cs_default_touch_rate.MSG_STATUS_TIME
     *
     * @mbggenerated
     */
    public Long getMsgStatusTime() {
        return msgStatusTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_default_touch_rate.MSG_STATUS_TIME
     *
     * @param msgStatusTime the value for cs_default_touch_rate.MSG_STATUS_TIME
     *
     * @mbggenerated
     */
    public void setMsgStatusTime(Long msgStatusTime) {
        this.msgStatusTime = msgStatusTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_default_touch_rate.MSG_STATUS_TIME_TYPE
     *
     * @return the value of cs_default_touch_rate.MSG_STATUS_TIME_TYPE
     *
     * @mbggenerated
     */
    public Integer getMsgStatusTimeType() {
        return msgStatusTimeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_default_touch_rate.MSG_STATUS_TIME_TYPE
     *
     * @param msgStatusTimeType the value for cs_default_touch_rate.MSG_STATUS_TIME_TYPE
     *
     * @mbggenerated
     */
    public void setMsgStatusTimeType(Integer msgStatusTimeType) {
        this.msgStatusTimeType = msgStatusTimeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_default_touch_rate.MSG_UNLOAD_TIME
     *
     * @return the value of cs_default_touch_rate.MSG_UNLOAD_TIME
     *
     * @mbggenerated
     */
    public Long getMsgUnloadTime() {
        return msgUnloadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_default_touch_rate.MSG_UNLOAD_TIME
     *
     * @param msgUnloadTime the value for cs_default_touch_rate.MSG_UNLOAD_TIME
     *
     * @mbggenerated
     */
    public void setMsgUnloadTime(Long msgUnloadTime) {
        this.msgUnloadTime = msgUnloadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_default_touch_rate.MSG_UNLOAD_TIME_TYPE
     *
     * @return the value of cs_default_touch_rate.MSG_UNLOAD_TIME_TYPE
     *
     * @mbggenerated
     */
    public Integer getMsgUnloadTimeType() {
        return msgUnloadTimeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_default_touch_rate.MSG_UNLOAD_TIME_TYPE
     *
     * @param msgUnloadTimeType the value for cs_default_touch_rate.MSG_UNLOAD_TIME_TYPE
     *
     * @mbggenerated
     */
    public void setMsgUnloadTimeType(Integer msgUnloadTimeType) {
        this.msgUnloadTimeType = msgUnloadTimeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_default_touch_rate.PUSH_RESERV_INFO_TIME
     *
     * @return the value of cs_default_touch_rate.PUSH_RESERV_INFO_TIME
     *
     * @mbggenerated
     */
    public Long getPushReservInfoTime() {
        return pushReservInfoTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_default_touch_rate.PUSH_RESERV_INFO_TIME
     *
     * @param pushReservInfoTime the value for cs_default_touch_rate.PUSH_RESERV_INFO_TIME
     *
     * @mbggenerated
     */
    public void setPushReservInfoTime(Long pushReservInfoTime) {
        this.pushReservInfoTime = pushReservInfoTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_default_touch_rate.PUSH_RESERV_INFO_TIME_TYPE
     *
     * @return the value of cs_default_touch_rate.PUSH_RESERV_INFO_TIME_TYPE
     *
     * @mbggenerated
     */
    public Integer getPushReservInfoTimeType() {
        return pushReservInfoTimeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_default_touch_rate.PUSH_RESERV_INFO_TIME_TYPE
     *
     * @param pushReservInfoTimeType the value for cs_default_touch_rate.PUSH_RESERV_INFO_TIME_TYPE
     *
     * @mbggenerated
     */
    public void setPushReservInfoTimeType(Integer pushReservInfoTimeType) {
        this.pushReservInfoTimeType = pushReservInfoTimeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_default_touch_rate.PUSH_STATUS_TIME
     *
     * @return the value of cs_default_touch_rate.PUSH_STATUS_TIME
     *
     * @mbggenerated
     */
    public Long getPushStatusTime() {
        return pushStatusTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_default_touch_rate.PUSH_STATUS_TIME
     *
     * @param pushStatusTime the value for cs_default_touch_rate.PUSH_STATUS_TIME
     *
     * @mbggenerated
     */
    public void setPushStatusTime(Long pushStatusTime) {
        this.pushStatusTime = pushStatusTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_default_touch_rate.PUSH_STATUS_TIME_TYPE
     *
     * @return the value of cs_default_touch_rate.PUSH_STATUS_TIME_TYPE
     *
     * @mbggenerated
     */
    public Integer getPushStatusTimeType() {
        return pushStatusTimeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_default_touch_rate.PUSH_STATUS_TIME_TYPE
     *
     * @param pushStatusTimeType the value for cs_default_touch_rate.PUSH_STATUS_TIME_TYPE
     *
     * @mbggenerated
     */
    public void setPushStatusTimeType(Integer pushStatusTimeType) {
        this.pushStatusTimeType = pushStatusTimeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_default_touch_rate.PUSH_UN_REGISTER
     *
     * @return the value of cs_default_touch_rate.PUSH_UN_REGISTER
     *
     * @mbggenerated
     */
    public Long getPushUnRegister() {
        return pushUnRegister;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_default_touch_rate.PUSH_UN_REGISTER
     *
     * @param pushUnRegister the value for cs_default_touch_rate.PUSH_UN_REGISTER
     *
     * @mbggenerated
     */
    public void setPushUnRegister(Long pushUnRegister) {
        this.pushUnRegister = pushUnRegister;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_default_touch_rate.PUSH_UN_REGISTER_TYPE
     *
     * @return the value of cs_default_touch_rate.PUSH_UN_REGISTER_TYPE
     *
     * @mbggenerated
     */
    public Integer getPushUnRegisterType() {
        return pushUnRegisterType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_default_touch_rate.PUSH_UN_REGISTER_TYPE
     *
     * @param pushUnRegisterType the value for cs_default_touch_rate.PUSH_UN_REGISTER_TYPE
     *
     * @mbggenerated
     */
    public void setPushUnRegisterType(Integer pushUnRegisterType) {
        this.pushUnRegisterType = pushUnRegisterType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_default_touch_rate
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", nId=").append(nId);
        sb.append(", str0=").append(str0);
        sb.append(", str1=").append(str1);
        sb.append(", compId=").append(compId);
        sb.append(", createBy=").append(createBy);
        sb.append(", createTime=").append(createTime);
        sb.append(", modiBy=").append(modiBy);
        sb.append(", modiTime=").append(modiTime);
        sb.append(", orgId=").append(orgId);
        sb.append(", sortNum=").append(sortNum);
        sb.append(", status=").append(status);
        sb.append(", msgStatusTime=").append(msgStatusTime);
        sb.append(", msgStatusTimeType=").append(msgStatusTimeType);
        sb.append(", msgUnloadTime=").append(msgUnloadTime);
        sb.append(", msgUnloadTimeType=").append(msgUnloadTimeType);
        sb.append(", pushReservInfoTime=").append(pushReservInfoTime);
        sb.append(", pushReservInfoTimeType=").append(pushReservInfoTimeType);
        sb.append(", pushStatusTime=").append(pushStatusTime);
        sb.append(", pushStatusTimeType=").append(pushStatusTimeType);
        sb.append(", pushUnRegister=").append(pushUnRegister);
        sb.append(", pushUnRegisterType=").append(pushUnRegisterType);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}