package top.lover.hyperlink.entity;

import java.io.Serializable;
import java.util.Date;

public class CsOverviewRecords implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_overview_records.N_ID
     *
     * @mbggenerated
     */
    private Long nId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_overview_records.CHANNEL
     *
     * @mbggenerated
     */
    private Long channel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_overview_records.PHONE_SERIAL_NUM
     *
     * @mbggenerated
     */
    private String phoneSerialNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_overview_records.PHONE
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_overview_records.PV
     *
     * @mbggenerated
     */
    private Integer pv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_overview_records.UV
     *
     * @mbggenerated
     */
    private Integer uv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_overview_records.DOWNLOAD_NUM
     *
     * @mbggenerated
     */
    private Integer downloadNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_overview_records.INSTALL_NUM
     *
     * @mbggenerated
     */
    private Integer installNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_overview_records.REGISTER_NUM
     *
     * @mbggenerated
     */
    private Integer registerNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_overview_records.UNINSTALL_NUM
     *
     * @mbggenerated
     */
    private Integer uninstallNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_overview_records.STARTUP_NUM
     *
     * @mbggenerated
     */
    private Integer startupNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_overview_records.RECEPTION_SURATION
     *
     * @mbggenerated
     */
    private Long receptionSuration;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_overview_records.BACKSTAGE_SURATION
     *
     * @mbggenerated
     */
    private Long backstageSuration;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_overview_records.RETAIN_DATA_NUM
     *
     * @mbggenerated
     */
    private Integer retainDataNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_overview_records.VISIT_RECENT_TIME
     *
     * @mbggenerated
     */
    private Date visitRecentTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_overview_records.DOWNLOAD_RECENT_TIME
     *
     * @mbggenerated
     */
    private Date downloadRecentTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_overview_records.INSTALL_RECENT_TIME
     *
     * @mbggenerated
     */
    private Date installRecentTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_overview_records.REGISTER_RECENT_TIME
     *
     * @mbggenerated
     */
    private Date registerRecentTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_overview_records.UNINSTALL_RECENT_TIME
     *
     * @mbggenerated
     */
    private Date uninstallRecentTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_overview_records.PUSH_RECENT_TIME
     *
     * @mbggenerated
     */
    private Date pushRecentTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_overview_records.SMS_RECENT_TIME
     *
     * @mbggenerated
     */
    private Date smsRecentTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_overview_records.SYSTEM_TYPE
     *
     * @mbggenerated
     */
    private Integer systemType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_overview_records.STR0
     *
     * @mbggenerated
     */
    private String str0;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_overview_records.STR1
     *
     * @mbggenerated
     */
    private String str1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_overview_records.COMP_ID
     *
     * @mbggenerated
     */
    private Long compId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_overview_records.CREATE_BY
     *
     * @mbggenerated
     */
    private Long createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_overview_records.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_overview_records.MODI_BY
     *
     * @mbggenerated
     */
    private Long modiBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_overview_records.MODI_TIME
     *
     * @mbggenerated
     */
    private Date modiTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_overview_records.ORG_ID
     *
     * @mbggenerated
     */
    private Long orgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_overview_records.SORT_NUM
     *
     * @mbggenerated
     */
    private Integer sortNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_overview_records.STATUS
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cs_overview_records
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_overview_records.N_ID
     *
     * @return the value of cs_overview_records.N_ID
     *
     * @mbggenerated
     */
    public Long getnId() {
        return nId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_overview_records.N_ID
     *
     * @param nId the value for cs_overview_records.N_ID
     *
     * @mbggenerated
     */
    public void setnId(Long nId) {
        this.nId = nId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_overview_records.CHANNEL
     *
     * @return the value of cs_overview_records.CHANNEL
     *
     * @mbggenerated
     */
    public Long getChannel() {
        return channel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_overview_records.CHANNEL
     *
     * @param channel the value for cs_overview_records.CHANNEL
     *
     * @mbggenerated
     */
    public void setChannel(Long channel) {
        this.channel = channel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_overview_records.PHONE_SERIAL_NUM
     *
     * @return the value of cs_overview_records.PHONE_SERIAL_NUM
     *
     * @mbggenerated
     */
    public String getPhoneSerialNum() {
        return phoneSerialNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_overview_records.PHONE_SERIAL_NUM
     *
     * @param phoneSerialNum the value for cs_overview_records.PHONE_SERIAL_NUM
     *
     * @mbggenerated
     */
    public void setPhoneSerialNum(String phoneSerialNum) {
        this.phoneSerialNum = phoneSerialNum == null ? null : phoneSerialNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_overview_records.PHONE
     *
     * @return the value of cs_overview_records.PHONE
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_overview_records.PHONE
     *
     * @param phone the value for cs_overview_records.PHONE
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_overview_records.PV
     *
     * @return the value of cs_overview_records.PV
     *
     * @mbggenerated
     */
    public Integer getPv() {
        return pv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_overview_records.PV
     *
     * @param pv the value for cs_overview_records.PV
     *
     * @mbggenerated
     */
    public void setPv(Integer pv) {
        this.pv = pv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_overview_records.UV
     *
     * @return the value of cs_overview_records.UV
     *
     * @mbggenerated
     */
    public Integer getUv() {
        return uv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_overview_records.UV
     *
     * @param uv the value for cs_overview_records.UV
     *
     * @mbggenerated
     */
    public void setUv(Integer uv) {
        this.uv = uv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_overview_records.DOWNLOAD_NUM
     *
     * @return the value of cs_overview_records.DOWNLOAD_NUM
     *
     * @mbggenerated
     */
    public Integer getDownloadNum() {
        return downloadNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_overview_records.DOWNLOAD_NUM
     *
     * @param downloadNum the value for cs_overview_records.DOWNLOAD_NUM
     *
     * @mbggenerated
     */
    public void setDownloadNum(Integer downloadNum) {
        this.downloadNum = downloadNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_overview_records.INSTALL_NUM
     *
     * @return the value of cs_overview_records.INSTALL_NUM
     *
     * @mbggenerated
     */
    public Integer getInstallNum() {
        return installNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_overview_records.INSTALL_NUM
     *
     * @param installNum the value for cs_overview_records.INSTALL_NUM
     *
     * @mbggenerated
     */
    public void setInstallNum(Integer installNum) {
        this.installNum = installNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_overview_records.REGISTER_NUM
     *
     * @return the value of cs_overview_records.REGISTER_NUM
     *
     * @mbggenerated
     */
    public Integer getRegisterNum() {
        return registerNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_overview_records.REGISTER_NUM
     *
     * @param registerNum the value for cs_overview_records.REGISTER_NUM
     *
     * @mbggenerated
     */
    public void setRegisterNum(Integer registerNum) {
        this.registerNum = registerNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_overview_records.UNINSTALL_NUM
     *
     * @return the value of cs_overview_records.UNINSTALL_NUM
     *
     * @mbggenerated
     */
    public Integer getUninstallNum() {
        return uninstallNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_overview_records.UNINSTALL_NUM
     *
     * @param uninstallNum the value for cs_overview_records.UNINSTALL_NUM
     *
     * @mbggenerated
     */
    public void setUninstallNum(Integer uninstallNum) {
        this.uninstallNum = uninstallNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_overview_records.STARTUP_NUM
     *
     * @return the value of cs_overview_records.STARTUP_NUM
     *
     * @mbggenerated
     */
    public Integer getStartupNum() {
        return startupNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_overview_records.STARTUP_NUM
     *
     * @param startupNum the value for cs_overview_records.STARTUP_NUM
     *
     * @mbggenerated
     */
    public void setStartupNum(Integer startupNum) {
        this.startupNum = startupNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_overview_records.RECEPTION_SURATION
     *
     * @return the value of cs_overview_records.RECEPTION_SURATION
     *
     * @mbggenerated
     */
    public Long getReceptionSuration() {
        return receptionSuration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_overview_records.RECEPTION_SURATION
     *
     * @param receptionSuration the value for cs_overview_records.RECEPTION_SURATION
     *
     * @mbggenerated
     */
    public void setReceptionSuration(Long receptionSuration) {
        this.receptionSuration = receptionSuration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_overview_records.BACKSTAGE_SURATION
     *
     * @return the value of cs_overview_records.BACKSTAGE_SURATION
     *
     * @mbggenerated
     */
    public Long getBackstageSuration() {
        return backstageSuration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_overview_records.BACKSTAGE_SURATION
     *
     * @param backstageSuration the value for cs_overview_records.BACKSTAGE_SURATION
     *
     * @mbggenerated
     */
    public void setBackstageSuration(Long backstageSuration) {
        this.backstageSuration = backstageSuration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_overview_records.RETAIN_DATA_NUM
     *
     * @return the value of cs_overview_records.RETAIN_DATA_NUM
     *
     * @mbggenerated
     */
    public Integer getRetainDataNum() {
        return retainDataNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_overview_records.RETAIN_DATA_NUM
     *
     * @param retainDataNum the value for cs_overview_records.RETAIN_DATA_NUM
     *
     * @mbggenerated
     */
    public void setRetainDataNum(Integer retainDataNum) {
        this.retainDataNum = retainDataNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_overview_records.VISIT_RECENT_TIME
     *
     * @return the value of cs_overview_records.VISIT_RECENT_TIME
     *
     * @mbggenerated
     */
    public Date getVisitRecentTime() {
        return visitRecentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_overview_records.VISIT_RECENT_TIME
     *
     * @param visitRecentTime the value for cs_overview_records.VISIT_RECENT_TIME
     *
     * @mbggenerated
     */
    public void setVisitRecentTime(Date visitRecentTime) {
        this.visitRecentTime = visitRecentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_overview_records.DOWNLOAD_RECENT_TIME
     *
     * @return the value of cs_overview_records.DOWNLOAD_RECENT_TIME
     *
     * @mbggenerated
     */
    public Date getDownloadRecentTime() {
        return downloadRecentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_overview_records.DOWNLOAD_RECENT_TIME
     *
     * @param downloadRecentTime the value for cs_overview_records.DOWNLOAD_RECENT_TIME
     *
     * @mbggenerated
     */
    public void setDownloadRecentTime(Date downloadRecentTime) {
        this.downloadRecentTime = downloadRecentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_overview_records.INSTALL_RECENT_TIME
     *
     * @return the value of cs_overview_records.INSTALL_RECENT_TIME
     *
     * @mbggenerated
     */
    public Date getInstallRecentTime() {
        return installRecentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_overview_records.INSTALL_RECENT_TIME
     *
     * @param installRecentTime the value for cs_overview_records.INSTALL_RECENT_TIME
     *
     * @mbggenerated
     */
    public void setInstallRecentTime(Date installRecentTime) {
        this.installRecentTime = installRecentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_overview_records.REGISTER_RECENT_TIME
     *
     * @return the value of cs_overview_records.REGISTER_RECENT_TIME
     *
     * @mbggenerated
     */
    public Date getRegisterRecentTime() {
        return registerRecentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_overview_records.REGISTER_RECENT_TIME
     *
     * @param registerRecentTime the value for cs_overview_records.REGISTER_RECENT_TIME
     *
     * @mbggenerated
     */
    public void setRegisterRecentTime(Date registerRecentTime) {
        this.registerRecentTime = registerRecentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_overview_records.UNINSTALL_RECENT_TIME
     *
     * @return the value of cs_overview_records.UNINSTALL_RECENT_TIME
     *
     * @mbggenerated
     */
    public Date getUninstallRecentTime() {
        return uninstallRecentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_overview_records.UNINSTALL_RECENT_TIME
     *
     * @param uninstallRecentTime the value for cs_overview_records.UNINSTALL_RECENT_TIME
     *
     * @mbggenerated
     */
    public void setUninstallRecentTime(Date uninstallRecentTime) {
        this.uninstallRecentTime = uninstallRecentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_overview_records.PUSH_RECENT_TIME
     *
     * @return the value of cs_overview_records.PUSH_RECENT_TIME
     *
     * @mbggenerated
     */
    public Date getPushRecentTime() {
        return pushRecentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_overview_records.PUSH_RECENT_TIME
     *
     * @param pushRecentTime the value for cs_overview_records.PUSH_RECENT_TIME
     *
     * @mbggenerated
     */
    public void setPushRecentTime(Date pushRecentTime) {
        this.pushRecentTime = pushRecentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_overview_records.SMS_RECENT_TIME
     *
     * @return the value of cs_overview_records.SMS_RECENT_TIME
     *
     * @mbggenerated
     */
    public Date getSmsRecentTime() {
        return smsRecentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_overview_records.SMS_RECENT_TIME
     *
     * @param smsRecentTime the value for cs_overview_records.SMS_RECENT_TIME
     *
     * @mbggenerated
     */
    public void setSmsRecentTime(Date smsRecentTime) {
        this.smsRecentTime = smsRecentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_overview_records.SYSTEM_TYPE
     *
     * @return the value of cs_overview_records.SYSTEM_TYPE
     *
     * @mbggenerated
     */
    public Integer getSystemType() {
        return systemType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_overview_records.SYSTEM_TYPE
     *
     * @param systemType the value for cs_overview_records.SYSTEM_TYPE
     *
     * @mbggenerated
     */
    public void setSystemType(Integer systemType) {
        this.systemType = systemType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_overview_records.STR0
     *
     * @return the value of cs_overview_records.STR0
     *
     * @mbggenerated
     */
    public String getStr0() {
        return str0;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_overview_records.STR0
     *
     * @param str0 the value for cs_overview_records.STR0
     *
     * @mbggenerated
     */
    public void setStr0(String str0) {
        this.str0 = str0 == null ? null : str0.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_overview_records.STR1
     *
     * @return the value of cs_overview_records.STR1
     *
     * @mbggenerated
     */
    public String getStr1() {
        return str1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_overview_records.STR1
     *
     * @param str1 the value for cs_overview_records.STR1
     *
     * @mbggenerated
     */
    public void setStr1(String str1) {
        this.str1 = str1 == null ? null : str1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_overview_records.COMP_ID
     *
     * @return the value of cs_overview_records.COMP_ID
     *
     * @mbggenerated
     */
    public Long getCompId() {
        return compId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_overview_records.COMP_ID
     *
     * @param compId the value for cs_overview_records.COMP_ID
     *
     * @mbggenerated
     */
    public void setCompId(Long compId) {
        this.compId = compId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_overview_records.CREATE_BY
     *
     * @return the value of cs_overview_records.CREATE_BY
     *
     * @mbggenerated
     */
    public Long getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_overview_records.CREATE_BY
     *
     * @param createBy the value for cs_overview_records.CREATE_BY
     *
     * @mbggenerated
     */
    public void setCreateBy(Long createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_overview_records.CREATE_TIME
     *
     * @return the value of cs_overview_records.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_overview_records.CREATE_TIME
     *
     * @param createTime the value for cs_overview_records.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_overview_records.MODI_BY
     *
     * @return the value of cs_overview_records.MODI_BY
     *
     * @mbggenerated
     */
    public Long getModiBy() {
        return modiBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_overview_records.MODI_BY
     *
     * @param modiBy the value for cs_overview_records.MODI_BY
     *
     * @mbggenerated
     */
    public void setModiBy(Long modiBy) {
        this.modiBy = modiBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_overview_records.MODI_TIME
     *
     * @return the value of cs_overview_records.MODI_TIME
     *
     * @mbggenerated
     */
    public Date getModiTime() {
        return modiTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_overview_records.MODI_TIME
     *
     * @param modiTime the value for cs_overview_records.MODI_TIME
     *
     * @mbggenerated
     */
    public void setModiTime(Date modiTime) {
        this.modiTime = modiTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_overview_records.ORG_ID
     *
     * @return the value of cs_overview_records.ORG_ID
     *
     * @mbggenerated
     */
    public Long getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_overview_records.ORG_ID
     *
     * @param orgId the value for cs_overview_records.ORG_ID
     *
     * @mbggenerated
     */
    public void setOrgId(Long orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_overview_records.SORT_NUM
     *
     * @return the value of cs_overview_records.SORT_NUM
     *
     * @mbggenerated
     */
    public Integer getSortNum() {
        return sortNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_overview_records.SORT_NUM
     *
     * @param sortNum the value for cs_overview_records.SORT_NUM
     *
     * @mbggenerated
     */
    public void setSortNum(Integer sortNum) {
        this.sortNum = sortNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_overview_records.STATUS
     *
     * @return the value of cs_overview_records.STATUS
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_overview_records.STATUS
     *
     * @param status the value for cs_overview_records.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_overview_records
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", nId=").append(nId);
        sb.append(", channel=").append(channel);
        sb.append(", phoneSerialNum=").append(phoneSerialNum);
        sb.append(", phone=").append(phone);
        sb.append(", pv=").append(pv);
        sb.append(", uv=").append(uv);
        sb.append(", downloadNum=").append(downloadNum);
        sb.append(", installNum=").append(installNum);
        sb.append(", registerNum=").append(registerNum);
        sb.append(", uninstallNum=").append(uninstallNum);
        sb.append(", startupNum=").append(startupNum);
        sb.append(", receptionSuration=").append(receptionSuration);
        sb.append(", backstageSuration=").append(backstageSuration);
        sb.append(", retainDataNum=").append(retainDataNum);
        sb.append(", visitRecentTime=").append(visitRecentTime);
        sb.append(", downloadRecentTime=").append(downloadRecentTime);
        sb.append(", installRecentTime=").append(installRecentTime);
        sb.append(", registerRecentTime=").append(registerRecentTime);
        sb.append(", uninstallRecentTime=").append(uninstallRecentTime);
        sb.append(", pushRecentTime=").append(pushRecentTime);
        sb.append(", smsRecentTime=").append(smsRecentTime);
        sb.append(", systemType=").append(systemType);
        sb.append(", str0=").append(str0);
        sb.append(", str1=").append(str1);
        sb.append(", compId=").append(compId);
        sb.append(", createBy=").append(createBy);
        sb.append(", createTime=").append(createTime);
        sb.append(", modiBy=").append(modiBy);
        sb.append(", modiTime=").append(modiTime);
        sb.append(", orgId=").append(orgId);
        sb.append(", sortNum=").append(sortNum);
        sb.append(", status=").append(status);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}