package top.lover.hyperlink.entity;

import java.io.Serializable;
import java.util.Date;

public class CsPushSet implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_push_set.N_ID
     *
     * @mbggenerated
     */
    private Long nId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_push_set.STR0
     *
     * @mbggenerated
     */
    private String str0;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_push_set.STR1
     *
     * @mbggenerated
     */
    private String str1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_push_set.COMP_ID
     *
     * @mbggenerated
     */
    private Long compId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_push_set.CREATE_BY
     *
     * @mbggenerated
     */
    private Long createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_push_set.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_push_set.MODI_BY
     *
     * @mbggenerated
     */
    private Long modiBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_push_set.MODI_TIME
     *
     * @mbggenerated
     */
    private Date modiTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_push_set.ORG_ID
     *
     * @mbggenerated
     */
    private Long orgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_push_set.SORT_NUM
     *
     * @mbggenerated
     */
    private Integer sortNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_push_set.STATUS
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_push_set.APP
     *
     * @mbggenerated
     */
    private Long app;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_push_set.APP_NAME
     *
     * @mbggenerated
     */
    private String appName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_push_set.CHANNEL
     *
     * @mbggenerated
     */
    private String channel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_push_set.INFORMATION
     *
     * @mbggenerated
     */
    private String information;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_push_set.IS_DEFAULT
     *
     * @mbggenerated
     */
    private String isDefault;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_push_set.PROCESS_LINK
     *
     * @mbggenerated
     */
    private Long processLink;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_push_set.PRODUCT_NAME
     *
     * @mbggenerated
     */
    private String productName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_push_set.USE_STATUS
     *
     * @mbggenerated
     */
    private Integer useStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_push_set.PRODUCT_ID
     *
     * @mbggenerated
     */
    private Long productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cs_push_set
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_push_set.N_ID
     *
     * @return the value of cs_push_set.N_ID
     *
     * @mbggenerated
     */
    public Long getnId() {
        return nId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_push_set.N_ID
     *
     * @param nId the value for cs_push_set.N_ID
     *
     * @mbggenerated
     */
    public void setnId(Long nId) {
        this.nId = nId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_push_set.STR0
     *
     * @return the value of cs_push_set.STR0
     *
     * @mbggenerated
     */
    public String getStr0() {
        return str0;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_push_set.STR0
     *
     * @param str0 the value for cs_push_set.STR0
     *
     * @mbggenerated
     */
    public void setStr0(String str0) {
        this.str0 = str0 == null ? null : str0.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_push_set.STR1
     *
     * @return the value of cs_push_set.STR1
     *
     * @mbggenerated
     */
    public String getStr1() {
        return str1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_push_set.STR1
     *
     * @param str1 the value for cs_push_set.STR1
     *
     * @mbggenerated
     */
    public void setStr1(String str1) {
        this.str1 = str1 == null ? null : str1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_push_set.COMP_ID
     *
     * @return the value of cs_push_set.COMP_ID
     *
     * @mbggenerated
     */
    public Long getCompId() {
        return compId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_push_set.COMP_ID
     *
     * @param compId the value for cs_push_set.COMP_ID
     *
     * @mbggenerated
     */
    public void setCompId(Long compId) {
        this.compId = compId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_push_set.CREATE_BY
     *
     * @return the value of cs_push_set.CREATE_BY
     *
     * @mbggenerated
     */
    public Long getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_push_set.CREATE_BY
     *
     * @param createBy the value for cs_push_set.CREATE_BY
     *
     * @mbggenerated
     */
    public void setCreateBy(Long createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_push_set.CREATE_TIME
     *
     * @return the value of cs_push_set.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_push_set.CREATE_TIME
     *
     * @param createTime the value for cs_push_set.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_push_set.MODI_BY
     *
     * @return the value of cs_push_set.MODI_BY
     *
     * @mbggenerated
     */
    public Long getModiBy() {
        return modiBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_push_set.MODI_BY
     *
     * @param modiBy the value for cs_push_set.MODI_BY
     *
     * @mbggenerated
     */
    public void setModiBy(Long modiBy) {
        this.modiBy = modiBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_push_set.MODI_TIME
     *
     * @return the value of cs_push_set.MODI_TIME
     *
     * @mbggenerated
     */
    public Date getModiTime() {
        return modiTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_push_set.MODI_TIME
     *
     * @param modiTime the value for cs_push_set.MODI_TIME
     *
     * @mbggenerated
     */
    public void setModiTime(Date modiTime) {
        this.modiTime = modiTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_push_set.ORG_ID
     *
     * @return the value of cs_push_set.ORG_ID
     *
     * @mbggenerated
     */
    public Long getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_push_set.ORG_ID
     *
     * @param orgId the value for cs_push_set.ORG_ID
     *
     * @mbggenerated
     */
    public void setOrgId(Long orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_push_set.SORT_NUM
     *
     * @return the value of cs_push_set.SORT_NUM
     *
     * @mbggenerated
     */
    public Integer getSortNum() {
        return sortNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_push_set.SORT_NUM
     *
     * @param sortNum the value for cs_push_set.SORT_NUM
     *
     * @mbggenerated
     */
    public void setSortNum(Integer sortNum) {
        this.sortNum = sortNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_push_set.STATUS
     *
     * @return the value of cs_push_set.STATUS
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_push_set.STATUS
     *
     * @param status the value for cs_push_set.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_push_set.APP
     *
     * @return the value of cs_push_set.APP
     *
     * @mbggenerated
     */
    public Long getApp() {
        return app;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_push_set.APP
     *
     * @param app the value for cs_push_set.APP
     *
     * @mbggenerated
     */
    public void setApp(Long app) {
        this.app = app;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_push_set.APP_NAME
     *
     * @return the value of cs_push_set.APP_NAME
     *
     * @mbggenerated
     */
    public String getAppName() {
        return appName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_push_set.APP_NAME
     *
     * @param appName the value for cs_push_set.APP_NAME
     *
     * @mbggenerated
     */
    public void setAppName(String appName) {
        this.appName = appName == null ? null : appName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_push_set.CHANNEL
     *
     * @return the value of cs_push_set.CHANNEL
     *
     * @mbggenerated
     */
    public String getChannel() {
        return channel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_push_set.CHANNEL
     *
     * @param channel the value for cs_push_set.CHANNEL
     *
     * @mbggenerated
     */
    public void setChannel(String channel) {
        this.channel = channel == null ? null : channel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_push_set.INFORMATION
     *
     * @return the value of cs_push_set.INFORMATION
     *
     * @mbggenerated
     */
    public String getInformation() {
        return information;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_push_set.INFORMATION
     *
     * @param information the value for cs_push_set.INFORMATION
     *
     * @mbggenerated
     */
    public void setInformation(String information) {
        this.information = information == null ? null : information.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_push_set.IS_DEFAULT
     *
     * @return the value of cs_push_set.IS_DEFAULT
     *
     * @mbggenerated
     */
    public String getIsDefault() {
        return isDefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_push_set.IS_DEFAULT
     *
     * @param isDefault the value for cs_push_set.IS_DEFAULT
     *
     * @mbggenerated
     */
    public void setIsDefault(String isDefault) {
        this.isDefault = isDefault == null ? null : isDefault.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_push_set.PROCESS_LINK
     *
     * @return the value of cs_push_set.PROCESS_LINK
     *
     * @mbggenerated
     */
    public Long getProcessLink() {
        return processLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_push_set.PROCESS_LINK
     *
     * @param processLink the value for cs_push_set.PROCESS_LINK
     *
     * @mbggenerated
     */
    public void setProcessLink(Long processLink) {
        this.processLink = processLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_push_set.PRODUCT_NAME
     *
     * @return the value of cs_push_set.PRODUCT_NAME
     *
     * @mbggenerated
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_push_set.PRODUCT_NAME
     *
     * @param productName the value for cs_push_set.PRODUCT_NAME
     *
     * @mbggenerated
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_push_set.USE_STATUS
     *
     * @return the value of cs_push_set.USE_STATUS
     *
     * @mbggenerated
     */
    public Integer getUseStatus() {
        return useStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_push_set.USE_STATUS
     *
     * @param useStatus the value for cs_push_set.USE_STATUS
     *
     * @mbggenerated
     */
    public void setUseStatus(Integer useStatus) {
        this.useStatus = useStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_push_set.PRODUCT_ID
     *
     * @return the value of cs_push_set.PRODUCT_ID
     *
     * @mbggenerated
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_push_set.PRODUCT_ID
     *
     * @param productId the value for cs_push_set.PRODUCT_ID
     *
     * @mbggenerated
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_push_set
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", nId=").append(nId);
        sb.append(", str0=").append(str0);
        sb.append(", str1=").append(str1);
        sb.append(", compId=").append(compId);
        sb.append(", createBy=").append(createBy);
        sb.append(", createTime=").append(createTime);
        sb.append(", modiBy=").append(modiBy);
        sb.append(", modiTime=").append(modiTime);
        sb.append(", orgId=").append(orgId);
        sb.append(", sortNum=").append(sortNum);
        sb.append(", status=").append(status);
        sb.append(", app=").append(app);
        sb.append(", appName=").append(appName);
        sb.append(", channel=").append(channel);
        sb.append(", information=").append(information);
        sb.append(", isDefault=").append(isDefault);
        sb.append(", processLink=").append(processLink);
        sb.append(", productName=").append(productName);
        sb.append(", useStatus=").append(useStatus);
        sb.append(", productId=").append(productId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}