package top.lover.hyperlink.entity;

import java.io.Serializable;
import java.util.Date;

public class CsPushRecord implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_push_record.N_ID
     *
     * @mbggenerated
     */
    private Long nId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_push_record.PUSH_SET_ID
     *
     * @mbggenerated
     */
    private Long pushSetId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_push_record.PHONE_RESIAL_NUM
     *
     * @mbggenerated
     */
    private String phoneResialNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_push_record.STEP_POSITION
     *
     * @mbggenerated
     */
    private Integer stepPosition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_push_record.OPERATOR
     *
     * @mbggenerated
     */
    private Long operator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_push_record.STR0
     *
     * @mbggenerated
     */
    private String str0;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_push_record.STR1
     *
     * @mbggenerated
     */
    private String str1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_push_record.COMP_ID
     *
     * @mbggenerated
     */
    private Long compId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_push_record.CREATE_BY
     *
     * @mbggenerated
     */
    private Long createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_push_record.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_push_record.MODI_BY
     *
     * @mbggenerated
     */
    private Long modiBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_push_record.MODI_TIME
     *
     * @mbggenerated
     */
    private Date modiTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_push_record.ORG_ID
     *
     * @mbggenerated
     */
    private Long orgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_push_record.SORT_NUM
     *
     * @mbggenerated
     */
    private Integer sortNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_push_record.STATUS
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_push_record.CHANNEL
     *
     * @mbggenerated
     */
    private Long channel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_push_record.PRODUCT
     *
     * @mbggenerated
     */
    private Long product;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_push_record.PUSH_TYPE
     *
     * @mbggenerated
     */
    private Integer pushType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_push_record.PUSH_STATUS
     *
     * @mbggenerated
     */
    private Integer pushStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_push_record.phoneNumber
     *
     * @mbggenerated
     */
    private String phonenumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_push_record.PHONE
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cs_push_record
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_push_record.N_ID
     *
     * @return the value of cs_push_record.N_ID
     *
     * @mbggenerated
     */
    public Long getnId() {
        return nId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_push_record.N_ID
     *
     * @param nId the value for cs_push_record.N_ID
     *
     * @mbggenerated
     */
    public void setnId(Long nId) {
        this.nId = nId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_push_record.PUSH_SET_ID
     *
     * @return the value of cs_push_record.PUSH_SET_ID
     *
     * @mbggenerated
     */
    public Long getPushSetId() {
        return pushSetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_push_record.PUSH_SET_ID
     *
     * @param pushSetId the value for cs_push_record.PUSH_SET_ID
     *
     * @mbggenerated
     */
    public void setPushSetId(Long pushSetId) {
        this.pushSetId = pushSetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_push_record.PHONE_RESIAL_NUM
     *
     * @return the value of cs_push_record.PHONE_RESIAL_NUM
     *
     * @mbggenerated
     */
    public String getPhoneResialNum() {
        return phoneResialNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_push_record.PHONE_RESIAL_NUM
     *
     * @param phoneResialNum the value for cs_push_record.PHONE_RESIAL_NUM
     *
     * @mbggenerated
     */
    public void setPhoneResialNum(String phoneResialNum) {
        this.phoneResialNum = phoneResialNum == null ? null : phoneResialNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_push_record.STEP_POSITION
     *
     * @return the value of cs_push_record.STEP_POSITION
     *
     * @mbggenerated
     */
    public Integer getStepPosition() {
        return stepPosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_push_record.STEP_POSITION
     *
     * @param stepPosition the value for cs_push_record.STEP_POSITION
     *
     * @mbggenerated
     */
    public void setStepPosition(Integer stepPosition) {
        this.stepPosition = stepPosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_push_record.OPERATOR
     *
     * @return the value of cs_push_record.OPERATOR
     *
     * @mbggenerated
     */
    public Long getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_push_record.OPERATOR
     *
     * @param operator the value for cs_push_record.OPERATOR
     *
     * @mbggenerated
     */
    public void setOperator(Long operator) {
        this.operator = operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_push_record.STR0
     *
     * @return the value of cs_push_record.STR0
     *
     * @mbggenerated
     */
    public String getStr0() {
        return str0;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_push_record.STR0
     *
     * @param str0 the value for cs_push_record.STR0
     *
     * @mbggenerated
     */
    public void setStr0(String str0) {
        this.str0 = str0 == null ? null : str0.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_push_record.STR1
     *
     * @return the value of cs_push_record.STR1
     *
     * @mbggenerated
     */
    public String getStr1() {
        return str1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_push_record.STR1
     *
     * @param str1 the value for cs_push_record.STR1
     *
     * @mbggenerated
     */
    public void setStr1(String str1) {
        this.str1 = str1 == null ? null : str1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_push_record.COMP_ID
     *
     * @return the value of cs_push_record.COMP_ID
     *
     * @mbggenerated
     */
    public Long getCompId() {
        return compId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_push_record.COMP_ID
     *
     * @param compId the value for cs_push_record.COMP_ID
     *
     * @mbggenerated
     */
    public void setCompId(Long compId) {
        this.compId = compId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_push_record.CREATE_BY
     *
     * @return the value of cs_push_record.CREATE_BY
     *
     * @mbggenerated
     */
    public Long getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_push_record.CREATE_BY
     *
     * @param createBy the value for cs_push_record.CREATE_BY
     *
     * @mbggenerated
     */
    public void setCreateBy(Long createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_push_record.CREATE_TIME
     *
     * @return the value of cs_push_record.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_push_record.CREATE_TIME
     *
     * @param createTime the value for cs_push_record.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_push_record.MODI_BY
     *
     * @return the value of cs_push_record.MODI_BY
     *
     * @mbggenerated
     */
    public Long getModiBy() {
        return modiBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_push_record.MODI_BY
     *
     * @param modiBy the value for cs_push_record.MODI_BY
     *
     * @mbggenerated
     */
    public void setModiBy(Long modiBy) {
        this.modiBy = modiBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_push_record.MODI_TIME
     *
     * @return the value of cs_push_record.MODI_TIME
     *
     * @mbggenerated
     */
    public Date getModiTime() {
        return modiTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_push_record.MODI_TIME
     *
     * @param modiTime the value for cs_push_record.MODI_TIME
     *
     * @mbggenerated
     */
    public void setModiTime(Date modiTime) {
        this.modiTime = modiTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_push_record.ORG_ID
     *
     * @return the value of cs_push_record.ORG_ID
     *
     * @mbggenerated
     */
    public Long getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_push_record.ORG_ID
     *
     * @param orgId the value for cs_push_record.ORG_ID
     *
     * @mbggenerated
     */
    public void setOrgId(Long orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_push_record.SORT_NUM
     *
     * @return the value of cs_push_record.SORT_NUM
     *
     * @mbggenerated
     */
    public Integer getSortNum() {
        return sortNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_push_record.SORT_NUM
     *
     * @param sortNum the value for cs_push_record.SORT_NUM
     *
     * @mbggenerated
     */
    public void setSortNum(Integer sortNum) {
        this.sortNum = sortNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_push_record.STATUS
     *
     * @return the value of cs_push_record.STATUS
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_push_record.STATUS
     *
     * @param status the value for cs_push_record.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_push_record.CHANNEL
     *
     * @return the value of cs_push_record.CHANNEL
     *
     * @mbggenerated
     */
    public Long getChannel() {
        return channel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_push_record.CHANNEL
     *
     * @param channel the value for cs_push_record.CHANNEL
     *
     * @mbggenerated
     */
    public void setChannel(Long channel) {
        this.channel = channel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_push_record.PRODUCT
     *
     * @return the value of cs_push_record.PRODUCT
     *
     * @mbggenerated
     */
    public Long getProduct() {
        return product;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_push_record.PRODUCT
     *
     * @param product the value for cs_push_record.PRODUCT
     *
     * @mbggenerated
     */
    public void setProduct(Long product) {
        this.product = product;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_push_record.PUSH_TYPE
     *
     * @return the value of cs_push_record.PUSH_TYPE
     *
     * @mbggenerated
     */
    public Integer getPushType() {
        return pushType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_push_record.PUSH_TYPE
     *
     * @param pushType the value for cs_push_record.PUSH_TYPE
     *
     * @mbggenerated
     */
    public void setPushType(Integer pushType) {
        this.pushType = pushType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_push_record.PUSH_STATUS
     *
     * @return the value of cs_push_record.PUSH_STATUS
     *
     * @mbggenerated
     */
    public Integer getPushStatus() {
        return pushStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_push_record.PUSH_STATUS
     *
     * @param pushStatus the value for cs_push_record.PUSH_STATUS
     *
     * @mbggenerated
     */
    public void setPushStatus(Integer pushStatus) {
        this.pushStatus = pushStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_push_record.phoneNumber
     *
     * @return the value of cs_push_record.phoneNumber
     *
     * @mbggenerated
     */
    public String getPhonenumber() {
        return phonenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_push_record.phoneNumber
     *
     * @param phonenumber the value for cs_push_record.phoneNumber
     *
     * @mbggenerated
     */
    public void setPhonenumber(String phonenumber) {
        this.phonenumber = phonenumber == null ? null : phonenumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_push_record.PHONE
     *
     * @return the value of cs_push_record.PHONE
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_push_record.PHONE
     *
     * @param phone the value for cs_push_record.PHONE
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_push_record
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", nId=").append(nId);
        sb.append(", pushSetId=").append(pushSetId);
        sb.append(", phoneResialNum=").append(phoneResialNum);
        sb.append(", stepPosition=").append(stepPosition);
        sb.append(", operator=").append(operator);
        sb.append(", str0=").append(str0);
        sb.append(", str1=").append(str1);
        sb.append(", compId=").append(compId);
        sb.append(", createBy=").append(createBy);
        sb.append(", createTime=").append(createTime);
        sb.append(", modiBy=").append(modiBy);
        sb.append(", modiTime=").append(modiTime);
        sb.append(", orgId=").append(orgId);
        sb.append(", sortNum=").append(sortNum);
        sb.append(", status=").append(status);
        sb.append(", channel=").append(channel);
        sb.append(", product=").append(product);
        sb.append(", pushType=").append(pushType);
        sb.append(", pushStatus=").append(pushStatus);
        sb.append(", phonenumber=").append(phonenumber);
        sb.append(", phone=").append(phone);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}