package top.lover.hyperlink.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class CsRetainDataStatistics implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_retain_data_statistics.N_ID
     *
     * @mbggenerated
     */
    private Long nId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_retain_data_statistics.CHANNEL
     *
     * @mbggenerated
     */
    private Long channel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_retain_data_statistics.PRODUCT
     *
     * @mbggenerated
     */
    private Long product;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_retain_data_statistics.PHONE
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_retain_data_statistics.TIME_DEFFERENCE
     *
     * @mbggenerated
     */
    private Long timeDefference;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_retain_data_statistics.IS_TOUCHUP_SMS
     *
     * @mbggenerated
     */
    private Integer isTouchupSms;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_retain_data_statistics.TOUCHUP_SMS_TYPE
     *
     * @mbggenerated
     */
    private Integer touchupSmsType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_retain_data_statistics.TOUCHUP_SMS_MANAGER
     *
     * @mbggenerated
     */
    private Long touchupSmsManager;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_retain_data_statistics.IS_TOUCHUP_PUSH
     *
     * @mbggenerated
     */
    private Integer isTouchupPush;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_retain_data_statistics.TOUCHUP_PUSH_TYPE
     *
     * @mbggenerated
     */
    private Integer touchupPushType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_retain_data_statistics.TOUCHUP_PUSH_MANAGER
     *
     * @mbggenerated
     */
    private Long touchupPushManager;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_retain_data_statistics.IS_RESERVE_DATA
     *
     * @mbggenerated
     */
    private Integer isReserveData;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_retain_data_statistics.CLOSE_RESERVE_TIME
     *
     * @mbggenerated
     */
    private Date closeReserveTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_retain_data_statistics.CREDIT_REPORT_FRACTION
     *
     * @mbggenerated
     */
    private BigDecimal creditReportFraction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_retain_data_statistics.STR0
     *
     * @mbggenerated
     */
    private String str0;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_retain_data_statistics.STR1
     *
     * @mbggenerated
     */
    private String str1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_retain_data_statistics.COMP_ID
     *
     * @mbggenerated
     */
    private Long compId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_retain_data_statistics.CREATE_BY
     *
     * @mbggenerated
     */
    private Long createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_retain_data_statistics.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_retain_data_statistics.MODI_BY
     *
     * @mbggenerated
     */
    private Long modiBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_retain_data_statistics.MODI_TIME
     *
     * @mbggenerated
     */
    private Date modiTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_retain_data_statistics.ORG_ID
     *
     * @mbggenerated
     */
    private Long orgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_retain_data_statistics.SORT_NUM
     *
     * @mbggenerated
     */
    private Integer sortNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_retain_data_statistics.STATUS
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_retain_data_statistics.PRODUCT_NAME
     *
     * @mbggenerated
     */
    private String productName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_retain_data_statistics.BANK_SCORE
     *
     * @mbggenerated
     */
    private Integer bankScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_retain_data_statistics.BEFOR_SCORE
     *
     * @mbggenerated
     */
    private Integer beforScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_retain_data_statistics.INTEL_SCORE
     *
     * @mbggenerated
     */
    private Integer intelScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_retain_data_statistics.LOAN_SCORE
     *
     * @mbggenerated
     */
    private Integer loanScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cs_retain_data_statistics
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_retain_data_statistics.N_ID
     *
     * @return the value of cs_retain_data_statistics.N_ID
     *
     * @mbggenerated
     */
    public Long getnId() {
        return nId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_retain_data_statistics.N_ID
     *
     * @param nId the value for cs_retain_data_statistics.N_ID
     *
     * @mbggenerated
     */
    public void setnId(Long nId) {
        this.nId = nId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_retain_data_statistics.CHANNEL
     *
     * @return the value of cs_retain_data_statistics.CHANNEL
     *
     * @mbggenerated
     */
    public Long getChannel() {
        return channel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_retain_data_statistics.CHANNEL
     *
     * @param channel the value for cs_retain_data_statistics.CHANNEL
     *
     * @mbggenerated
     */
    public void setChannel(Long channel) {
        this.channel = channel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_retain_data_statistics.PRODUCT
     *
     * @return the value of cs_retain_data_statistics.PRODUCT
     *
     * @mbggenerated
     */
    public Long getProduct() {
        return product;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_retain_data_statistics.PRODUCT
     *
     * @param product the value for cs_retain_data_statistics.PRODUCT
     *
     * @mbggenerated
     */
    public void setProduct(Long product) {
        this.product = product;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_retain_data_statistics.PHONE
     *
     * @return the value of cs_retain_data_statistics.PHONE
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_retain_data_statistics.PHONE
     *
     * @param phone the value for cs_retain_data_statistics.PHONE
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_retain_data_statistics.TIME_DEFFERENCE
     *
     * @return the value of cs_retain_data_statistics.TIME_DEFFERENCE
     *
     * @mbggenerated
     */
    public Long getTimeDefference() {
        return timeDefference;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_retain_data_statistics.TIME_DEFFERENCE
     *
     * @param timeDefference the value for cs_retain_data_statistics.TIME_DEFFERENCE
     *
     * @mbggenerated
     */
    public void setTimeDefference(Long timeDefference) {
        this.timeDefference = timeDefference;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_retain_data_statistics.IS_TOUCHUP_SMS
     *
     * @return the value of cs_retain_data_statistics.IS_TOUCHUP_SMS
     *
     * @mbggenerated
     */
    public Integer getIsTouchupSms() {
        return isTouchupSms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_retain_data_statistics.IS_TOUCHUP_SMS
     *
     * @param isTouchupSms the value for cs_retain_data_statistics.IS_TOUCHUP_SMS
     *
     * @mbggenerated
     */
    public void setIsTouchupSms(Integer isTouchupSms) {
        this.isTouchupSms = isTouchupSms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_retain_data_statistics.TOUCHUP_SMS_TYPE
     *
     * @return the value of cs_retain_data_statistics.TOUCHUP_SMS_TYPE
     *
     * @mbggenerated
     */
    public Integer getTouchupSmsType() {
        return touchupSmsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_retain_data_statistics.TOUCHUP_SMS_TYPE
     *
     * @param touchupSmsType the value for cs_retain_data_statistics.TOUCHUP_SMS_TYPE
     *
     * @mbggenerated
     */
    public void setTouchupSmsType(Integer touchupSmsType) {
        this.touchupSmsType = touchupSmsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_retain_data_statistics.TOUCHUP_SMS_MANAGER
     *
     * @return the value of cs_retain_data_statistics.TOUCHUP_SMS_MANAGER
     *
     * @mbggenerated
     */
    public Long getTouchupSmsManager() {
        return touchupSmsManager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_retain_data_statistics.TOUCHUP_SMS_MANAGER
     *
     * @param touchupSmsManager the value for cs_retain_data_statistics.TOUCHUP_SMS_MANAGER
     *
     * @mbggenerated
     */
    public void setTouchupSmsManager(Long touchupSmsManager) {
        this.touchupSmsManager = touchupSmsManager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_retain_data_statistics.IS_TOUCHUP_PUSH
     *
     * @return the value of cs_retain_data_statistics.IS_TOUCHUP_PUSH
     *
     * @mbggenerated
     */
    public Integer getIsTouchupPush() {
        return isTouchupPush;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_retain_data_statistics.IS_TOUCHUP_PUSH
     *
     * @param isTouchupPush the value for cs_retain_data_statistics.IS_TOUCHUP_PUSH
     *
     * @mbggenerated
     */
    public void setIsTouchupPush(Integer isTouchupPush) {
        this.isTouchupPush = isTouchupPush;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_retain_data_statistics.TOUCHUP_PUSH_TYPE
     *
     * @return the value of cs_retain_data_statistics.TOUCHUP_PUSH_TYPE
     *
     * @mbggenerated
     */
    public Integer getTouchupPushType() {
        return touchupPushType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_retain_data_statistics.TOUCHUP_PUSH_TYPE
     *
     * @param touchupPushType the value for cs_retain_data_statistics.TOUCHUP_PUSH_TYPE
     *
     * @mbggenerated
     */
    public void setTouchupPushType(Integer touchupPushType) {
        this.touchupPushType = touchupPushType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_retain_data_statistics.TOUCHUP_PUSH_MANAGER
     *
     * @return the value of cs_retain_data_statistics.TOUCHUP_PUSH_MANAGER
     *
     * @mbggenerated
     */
    public Long getTouchupPushManager() {
        return touchupPushManager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_retain_data_statistics.TOUCHUP_PUSH_MANAGER
     *
     * @param touchupPushManager the value for cs_retain_data_statistics.TOUCHUP_PUSH_MANAGER
     *
     * @mbggenerated
     */
    public void setTouchupPushManager(Long touchupPushManager) {
        this.touchupPushManager = touchupPushManager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_retain_data_statistics.IS_RESERVE_DATA
     *
     * @return the value of cs_retain_data_statistics.IS_RESERVE_DATA
     *
     * @mbggenerated
     */
    public Integer getIsReserveData() {
        return isReserveData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_retain_data_statistics.IS_RESERVE_DATA
     *
     * @param isReserveData the value for cs_retain_data_statistics.IS_RESERVE_DATA
     *
     * @mbggenerated
     */
    public void setIsReserveData(Integer isReserveData) {
        this.isReserveData = isReserveData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_retain_data_statistics.CLOSE_RESERVE_TIME
     *
     * @return the value of cs_retain_data_statistics.CLOSE_RESERVE_TIME
     *
     * @mbggenerated
     */
    public Date getCloseReserveTime() {
        return closeReserveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_retain_data_statistics.CLOSE_RESERVE_TIME
     *
     * @param closeReserveTime the value for cs_retain_data_statistics.CLOSE_RESERVE_TIME
     *
     * @mbggenerated
     */
    public void setCloseReserveTime(Date closeReserveTime) {
        this.closeReserveTime = closeReserveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_retain_data_statistics.CREDIT_REPORT_FRACTION
     *
     * @return the value of cs_retain_data_statistics.CREDIT_REPORT_FRACTION
     *
     * @mbggenerated
     */
    public BigDecimal getCreditReportFraction() {
        return creditReportFraction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_retain_data_statistics.CREDIT_REPORT_FRACTION
     *
     * @param creditReportFraction the value for cs_retain_data_statistics.CREDIT_REPORT_FRACTION
     *
     * @mbggenerated
     */
    public void setCreditReportFraction(BigDecimal creditReportFraction) {
        this.creditReportFraction = creditReportFraction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_retain_data_statistics.STR0
     *
     * @return the value of cs_retain_data_statistics.STR0
     *
     * @mbggenerated
     */
    public String getStr0() {
        return str0;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_retain_data_statistics.STR0
     *
     * @param str0 the value for cs_retain_data_statistics.STR0
     *
     * @mbggenerated
     */
    public void setStr0(String str0) {
        this.str0 = str0 == null ? null : str0.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_retain_data_statistics.STR1
     *
     * @return the value of cs_retain_data_statistics.STR1
     *
     * @mbggenerated
     */
    public String getStr1() {
        return str1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_retain_data_statistics.STR1
     *
     * @param str1 the value for cs_retain_data_statistics.STR1
     *
     * @mbggenerated
     */
    public void setStr1(String str1) {
        this.str1 = str1 == null ? null : str1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_retain_data_statistics.COMP_ID
     *
     * @return the value of cs_retain_data_statistics.COMP_ID
     *
     * @mbggenerated
     */
    public Long getCompId() {
        return compId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_retain_data_statistics.COMP_ID
     *
     * @param compId the value for cs_retain_data_statistics.COMP_ID
     *
     * @mbggenerated
     */
    public void setCompId(Long compId) {
        this.compId = compId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_retain_data_statistics.CREATE_BY
     *
     * @return the value of cs_retain_data_statistics.CREATE_BY
     *
     * @mbggenerated
     */
    public Long getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_retain_data_statistics.CREATE_BY
     *
     * @param createBy the value for cs_retain_data_statistics.CREATE_BY
     *
     * @mbggenerated
     */
    public void setCreateBy(Long createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_retain_data_statistics.CREATE_TIME
     *
     * @return the value of cs_retain_data_statistics.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_retain_data_statistics.CREATE_TIME
     *
     * @param createTime the value for cs_retain_data_statistics.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_retain_data_statistics.MODI_BY
     *
     * @return the value of cs_retain_data_statistics.MODI_BY
     *
     * @mbggenerated
     */
    public Long getModiBy() {
        return modiBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_retain_data_statistics.MODI_BY
     *
     * @param modiBy the value for cs_retain_data_statistics.MODI_BY
     *
     * @mbggenerated
     */
    public void setModiBy(Long modiBy) {
        this.modiBy = modiBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_retain_data_statistics.MODI_TIME
     *
     * @return the value of cs_retain_data_statistics.MODI_TIME
     *
     * @mbggenerated
     */
    public Date getModiTime() {
        return modiTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_retain_data_statistics.MODI_TIME
     *
     * @param modiTime the value for cs_retain_data_statistics.MODI_TIME
     *
     * @mbggenerated
     */
    public void setModiTime(Date modiTime) {
        this.modiTime = modiTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_retain_data_statistics.ORG_ID
     *
     * @return the value of cs_retain_data_statistics.ORG_ID
     *
     * @mbggenerated
     */
    public Long getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_retain_data_statistics.ORG_ID
     *
     * @param orgId the value for cs_retain_data_statistics.ORG_ID
     *
     * @mbggenerated
     */
    public void setOrgId(Long orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_retain_data_statistics.SORT_NUM
     *
     * @return the value of cs_retain_data_statistics.SORT_NUM
     *
     * @mbggenerated
     */
    public Integer getSortNum() {
        return sortNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_retain_data_statistics.SORT_NUM
     *
     * @param sortNum the value for cs_retain_data_statistics.SORT_NUM
     *
     * @mbggenerated
     */
    public void setSortNum(Integer sortNum) {
        this.sortNum = sortNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_retain_data_statistics.STATUS
     *
     * @return the value of cs_retain_data_statistics.STATUS
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_retain_data_statistics.STATUS
     *
     * @param status the value for cs_retain_data_statistics.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_retain_data_statistics.PRODUCT_NAME
     *
     * @return the value of cs_retain_data_statistics.PRODUCT_NAME
     *
     * @mbggenerated
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_retain_data_statistics.PRODUCT_NAME
     *
     * @param productName the value for cs_retain_data_statistics.PRODUCT_NAME
     *
     * @mbggenerated
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_retain_data_statistics.BANK_SCORE
     *
     * @return the value of cs_retain_data_statistics.BANK_SCORE
     *
     * @mbggenerated
     */
    public Integer getBankScore() {
        return bankScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_retain_data_statistics.BANK_SCORE
     *
     * @param bankScore the value for cs_retain_data_statistics.BANK_SCORE
     *
     * @mbggenerated
     */
    public void setBankScore(Integer bankScore) {
        this.bankScore = bankScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_retain_data_statistics.BEFOR_SCORE
     *
     * @return the value of cs_retain_data_statistics.BEFOR_SCORE
     *
     * @mbggenerated
     */
    public Integer getBeforScore() {
        return beforScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_retain_data_statistics.BEFOR_SCORE
     *
     * @param beforScore the value for cs_retain_data_statistics.BEFOR_SCORE
     *
     * @mbggenerated
     */
    public void setBeforScore(Integer beforScore) {
        this.beforScore = beforScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_retain_data_statistics.INTEL_SCORE
     *
     * @return the value of cs_retain_data_statistics.INTEL_SCORE
     *
     * @mbggenerated
     */
    public Integer getIntelScore() {
        return intelScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_retain_data_statistics.INTEL_SCORE
     *
     * @param intelScore the value for cs_retain_data_statistics.INTEL_SCORE
     *
     * @mbggenerated
     */
    public void setIntelScore(Integer intelScore) {
        this.intelScore = intelScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_retain_data_statistics.LOAN_SCORE
     *
     * @return the value of cs_retain_data_statistics.LOAN_SCORE
     *
     * @mbggenerated
     */
    public Integer getLoanScore() {
        return loanScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_retain_data_statistics.LOAN_SCORE
     *
     * @param loanScore the value for cs_retain_data_statistics.LOAN_SCORE
     *
     * @mbggenerated
     */
    public void setLoanScore(Integer loanScore) {
        this.loanScore = loanScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_retain_data_statistics
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", nId=").append(nId);
        sb.append(", channel=").append(channel);
        sb.append(", product=").append(product);
        sb.append(", phone=").append(phone);
        sb.append(", timeDefference=").append(timeDefference);
        sb.append(", isTouchupSms=").append(isTouchupSms);
        sb.append(", touchupSmsType=").append(touchupSmsType);
        sb.append(", touchupSmsManager=").append(touchupSmsManager);
        sb.append(", isTouchupPush=").append(isTouchupPush);
        sb.append(", touchupPushType=").append(touchupPushType);
        sb.append(", touchupPushManager=").append(touchupPushManager);
        sb.append(", isReserveData=").append(isReserveData);
        sb.append(", closeReserveTime=").append(closeReserveTime);
        sb.append(", creditReportFraction=").append(creditReportFraction);
        sb.append(", str0=").append(str0);
        sb.append(", str1=").append(str1);
        sb.append(", compId=").append(compId);
        sb.append(", createBy=").append(createBy);
        sb.append(", createTime=").append(createTime);
        sb.append(", modiBy=").append(modiBy);
        sb.append(", modiTime=").append(modiTime);
        sb.append(", orgId=").append(orgId);
        sb.append(", sortNum=").append(sortNum);
        sb.append(", status=").append(status);
        sb.append(", productName=").append(productName);
        sb.append(", bankScore=").append(bankScore);
        sb.append(", beforScore=").append(beforScore);
        sb.append(", intelScore=").append(intelScore);
        sb.append(", loanScore=").append(loanScore);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}