package top.lover.hyperlink.entity;

import java.io.Serializable;
import java.util.Date;

public class CsTouchupStatistics implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_touchup_statistics.N_ID
     *
     * @mbggenerated
     */
    private Long nId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_touchup_statistics.PRODUCT
     *
     * @mbggenerated
     */
    private Long product;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_touchup_statistics.TOUCHUP_NUM
     *
     * @mbggenerated
     */
    private Integer touchupNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_touchup_statistics.SUCCESS_NUM
     *
     * @mbggenerated
     */
    private Integer successNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_touchup_statistics.FAIL_NUM
     *
     * @mbggenerated
     */
    private Integer failNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_touchup_statistics.UNTREATED_NUM
     *
     * @mbggenerated
     */
    private Integer untreatedNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_touchup_statistics.OPERATOR
     *
     * @mbggenerated
     */
    private Long operator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_touchup_statistics.STR0
     *
     * @mbggenerated
     */
    private String str0;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_touchup_statistics.STR1
     *
     * @mbggenerated
     */
    private String str1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_touchup_statistics.COMP_ID
     *
     * @mbggenerated
     */
    private Long compId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_touchup_statistics.CREATE_BY
     *
     * @mbggenerated
     */
    private Long createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_touchup_statistics.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_touchup_statistics.MODI_BY
     *
     * @mbggenerated
     */
    private Long modiBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_touchup_statistics.MODI_TIME
     *
     * @mbggenerated
     */
    private Date modiTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_touchup_statistics.ORG_ID
     *
     * @mbggenerated
     */
    private Long orgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_touchup_statistics.SORT_NUM
     *
     * @mbggenerated
     */
    private Integer sortNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_touchup_statistics.STATUS
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cs_touchup_statistics
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_touchup_statistics.N_ID
     *
     * @return the value of cs_touchup_statistics.N_ID
     *
     * @mbggenerated
     */
    public Long getnId() {
        return nId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_touchup_statistics.N_ID
     *
     * @param nId the value for cs_touchup_statistics.N_ID
     *
     * @mbggenerated
     */
    public void setnId(Long nId) {
        this.nId = nId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_touchup_statistics.PRODUCT
     *
     * @return the value of cs_touchup_statistics.PRODUCT
     *
     * @mbggenerated
     */
    public Long getProduct() {
        return product;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_touchup_statistics.PRODUCT
     *
     * @param product the value for cs_touchup_statistics.PRODUCT
     *
     * @mbggenerated
     */
    public void setProduct(Long product) {
        this.product = product;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_touchup_statistics.TOUCHUP_NUM
     *
     * @return the value of cs_touchup_statistics.TOUCHUP_NUM
     *
     * @mbggenerated
     */
    public Integer getTouchupNum() {
        return touchupNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_touchup_statistics.TOUCHUP_NUM
     *
     * @param touchupNum the value for cs_touchup_statistics.TOUCHUP_NUM
     *
     * @mbggenerated
     */
    public void setTouchupNum(Integer touchupNum) {
        this.touchupNum = touchupNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_touchup_statistics.SUCCESS_NUM
     *
     * @return the value of cs_touchup_statistics.SUCCESS_NUM
     *
     * @mbggenerated
     */
    public Integer getSuccessNum() {
        return successNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_touchup_statistics.SUCCESS_NUM
     *
     * @param successNum the value for cs_touchup_statistics.SUCCESS_NUM
     *
     * @mbggenerated
     */
    public void setSuccessNum(Integer successNum) {
        this.successNum = successNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_touchup_statistics.FAIL_NUM
     *
     * @return the value of cs_touchup_statistics.FAIL_NUM
     *
     * @mbggenerated
     */
    public Integer getFailNum() {
        return failNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_touchup_statistics.FAIL_NUM
     *
     * @param failNum the value for cs_touchup_statistics.FAIL_NUM
     *
     * @mbggenerated
     */
    public void setFailNum(Integer failNum) {
        this.failNum = failNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_touchup_statistics.UNTREATED_NUM
     *
     * @return the value of cs_touchup_statistics.UNTREATED_NUM
     *
     * @mbggenerated
     */
    public Integer getUntreatedNum() {
        return untreatedNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_touchup_statistics.UNTREATED_NUM
     *
     * @param untreatedNum the value for cs_touchup_statistics.UNTREATED_NUM
     *
     * @mbggenerated
     */
    public void setUntreatedNum(Integer untreatedNum) {
        this.untreatedNum = untreatedNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_touchup_statistics.OPERATOR
     *
     * @return the value of cs_touchup_statistics.OPERATOR
     *
     * @mbggenerated
     */
    public Long getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_touchup_statistics.OPERATOR
     *
     * @param operator the value for cs_touchup_statistics.OPERATOR
     *
     * @mbggenerated
     */
    public void setOperator(Long operator) {
        this.operator = operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_touchup_statistics.STR0
     *
     * @return the value of cs_touchup_statistics.STR0
     *
     * @mbggenerated
     */
    public String getStr0() {
        return str0;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_touchup_statistics.STR0
     *
     * @param str0 the value for cs_touchup_statistics.STR0
     *
     * @mbggenerated
     */
    public void setStr0(String str0) {
        this.str0 = str0 == null ? null : str0.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_touchup_statistics.STR1
     *
     * @return the value of cs_touchup_statistics.STR1
     *
     * @mbggenerated
     */
    public String getStr1() {
        return str1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_touchup_statistics.STR1
     *
     * @param str1 the value for cs_touchup_statistics.STR1
     *
     * @mbggenerated
     */
    public void setStr1(String str1) {
        this.str1 = str1 == null ? null : str1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_touchup_statistics.COMP_ID
     *
     * @return the value of cs_touchup_statistics.COMP_ID
     *
     * @mbggenerated
     */
    public Long getCompId() {
        return compId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_touchup_statistics.COMP_ID
     *
     * @param compId the value for cs_touchup_statistics.COMP_ID
     *
     * @mbggenerated
     */
    public void setCompId(Long compId) {
        this.compId = compId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_touchup_statistics.CREATE_BY
     *
     * @return the value of cs_touchup_statistics.CREATE_BY
     *
     * @mbggenerated
     */
    public Long getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_touchup_statistics.CREATE_BY
     *
     * @param createBy the value for cs_touchup_statistics.CREATE_BY
     *
     * @mbggenerated
     */
    public void setCreateBy(Long createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_touchup_statistics.CREATE_TIME
     *
     * @return the value of cs_touchup_statistics.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_touchup_statistics.CREATE_TIME
     *
     * @param createTime the value for cs_touchup_statistics.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_touchup_statistics.MODI_BY
     *
     * @return the value of cs_touchup_statistics.MODI_BY
     *
     * @mbggenerated
     */
    public Long getModiBy() {
        return modiBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_touchup_statistics.MODI_BY
     *
     * @param modiBy the value for cs_touchup_statistics.MODI_BY
     *
     * @mbggenerated
     */
    public void setModiBy(Long modiBy) {
        this.modiBy = modiBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_touchup_statistics.MODI_TIME
     *
     * @return the value of cs_touchup_statistics.MODI_TIME
     *
     * @mbggenerated
     */
    public Date getModiTime() {
        return modiTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_touchup_statistics.MODI_TIME
     *
     * @param modiTime the value for cs_touchup_statistics.MODI_TIME
     *
     * @mbggenerated
     */
    public void setModiTime(Date modiTime) {
        this.modiTime = modiTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_touchup_statistics.ORG_ID
     *
     * @return the value of cs_touchup_statistics.ORG_ID
     *
     * @mbggenerated
     */
    public Long getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_touchup_statistics.ORG_ID
     *
     * @param orgId the value for cs_touchup_statistics.ORG_ID
     *
     * @mbggenerated
     */
    public void setOrgId(Long orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_touchup_statistics.SORT_NUM
     *
     * @return the value of cs_touchup_statistics.SORT_NUM
     *
     * @mbggenerated
     */
    public Integer getSortNum() {
        return sortNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_touchup_statistics.SORT_NUM
     *
     * @param sortNum the value for cs_touchup_statistics.SORT_NUM
     *
     * @mbggenerated
     */
    public void setSortNum(Integer sortNum) {
        this.sortNum = sortNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_touchup_statistics.STATUS
     *
     * @return the value of cs_touchup_statistics.STATUS
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_touchup_statistics.STATUS
     *
     * @param status the value for cs_touchup_statistics.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_touchup_statistics
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", nId=").append(nId);
        sb.append(", product=").append(product);
        sb.append(", touchupNum=").append(touchupNum);
        sb.append(", successNum=").append(successNum);
        sb.append(", failNum=").append(failNum);
        sb.append(", untreatedNum=").append(untreatedNum);
        sb.append(", operator=").append(operator);
        sb.append(", str0=").append(str0);
        sb.append(", str1=").append(str1);
        sb.append(", compId=").append(compId);
        sb.append(", createBy=").append(createBy);
        sb.append(", createTime=").append(createTime);
        sb.append(", modiBy=").append(modiBy);
        sb.append(", modiTime=").append(modiTime);
        sb.append(", orgId=").append(orgId);
        sb.append(", sortNum=").append(sortNum);
        sb.append(", status=").append(status);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}