package top.lover.hyperlink.entity;

import java.io.Serializable;
import java.util.Date;

public class TInfoTitle implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_info_title.N_ID
     *
     * @mbggenerated
     */
    private Long nId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_info_title.STR0
     *
     * @mbggenerated
     */
    private String str0;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_info_title.STR1
     *
     * @mbggenerated
     */
    private String str1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_info_title.COMP_ID
     *
     * @mbggenerated
     */
    private Long compId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_info_title.CREATE_BY
     *
     * @mbggenerated
     */
    private Long createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_info_title.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_info_title.MODI_BY
     *
     * @mbggenerated
     */
    private Long modiBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_info_title.MODI_TIME
     *
     * @mbggenerated
     */
    private Date modiTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_info_title.ORG_ID
     *
     * @mbggenerated
     */
    private Long orgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_info_title.SORT_NUM
     *
     * @mbggenerated
     */
    private Integer sortNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_info_title.STATUS
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_info_title.CON_TYPE
     *
     * @mbggenerated
     */
    private Integer conType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_info_title.DESCRIPT
     *
     * @mbggenerated
     */
    private String descript;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_info_title.IMAGE
     *
     * @mbggenerated
     */
    private String image;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_info_title.THUMBNAIL
     *
     * @mbggenerated
     */
    private String thumbnail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_info_title.INI_STATUS
     *
     * @mbggenerated
     */
    private Integer iniStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_info_title.KEY_WORDS
     *
     * @mbggenerated
     */
    private String keyWords;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_info_title.REC_TAGS
     *
     * @mbggenerated
     */
    private String recTags;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_info_title.RELEASE_TIME
     *
     * @mbggenerated
     */
    private Date releaseTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_info_title.RESOURCES
     *
     * @mbggenerated
     */
    private String resources;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_info_title.SUBTITLE
     *
     * @mbggenerated
     */
    private String subtitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_info_title.TITLE
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_info_title.REFUSE_CASE
     *
     * @mbggenerated
     */
    private String refuseCase;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_info_title.DURATION
     *
     * @mbggenerated
     */
    private String duration;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_info_title.CHANNEL_ID
     *
     * @mbggenerated
     */
    private Long channelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_info_title.CLASSIFY_ID
     *
     * @mbggenerated
     */
    private Long classifyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_info_title.PRODUCT_ID
     *
     * @mbggenerated
     */
    private Long productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_info_title.IS_RECOMMEND
     *
     * @mbggenerated
     */
    private Integer isRecommend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_info_title.AUDITOR
     *
     * @mbggenerated
     */
    private Long auditor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_info_title.AUDIT_TIME
     *
     * @mbggenerated
     */
    private Date auditTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_info_title.IS_MANAGE
     *
     * @mbggenerated
     */
    private Integer isManage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_info_title.CONTENT
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_info_title
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_info_title.N_ID
     *
     * @return the value of t_info_title.N_ID
     *
     * @mbggenerated
     */
    public Long getnId() {
        return nId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_info_title.N_ID
     *
     * @param nId the value for t_info_title.N_ID
     *
     * @mbggenerated
     */
    public void setnId(Long nId) {
        this.nId = nId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_info_title.STR0
     *
     * @return the value of t_info_title.STR0
     *
     * @mbggenerated
     */
    public String getStr0() {
        return str0;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_info_title.STR0
     *
     * @param str0 the value for t_info_title.STR0
     *
     * @mbggenerated
     */
    public void setStr0(String str0) {
        this.str0 = str0 == null ? null : str0.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_info_title.STR1
     *
     * @return the value of t_info_title.STR1
     *
     * @mbggenerated
     */
    public String getStr1() {
        return str1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_info_title.STR1
     *
     * @param str1 the value for t_info_title.STR1
     *
     * @mbggenerated
     */
    public void setStr1(String str1) {
        this.str1 = str1 == null ? null : str1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_info_title.COMP_ID
     *
     * @return the value of t_info_title.COMP_ID
     *
     * @mbggenerated
     */
    public Long getCompId() {
        return compId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_info_title.COMP_ID
     *
     * @param compId the value for t_info_title.COMP_ID
     *
     * @mbggenerated
     */
    public void setCompId(Long compId) {
        this.compId = compId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_info_title.CREATE_BY
     *
     * @return the value of t_info_title.CREATE_BY
     *
     * @mbggenerated
     */
    public Long getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_info_title.CREATE_BY
     *
     * @param createBy the value for t_info_title.CREATE_BY
     *
     * @mbggenerated
     */
    public void setCreateBy(Long createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_info_title.CREATE_TIME
     *
     * @return the value of t_info_title.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_info_title.CREATE_TIME
     *
     * @param createTime the value for t_info_title.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_info_title.MODI_BY
     *
     * @return the value of t_info_title.MODI_BY
     *
     * @mbggenerated
     */
    public Long getModiBy() {
        return modiBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_info_title.MODI_BY
     *
     * @param modiBy the value for t_info_title.MODI_BY
     *
     * @mbggenerated
     */
    public void setModiBy(Long modiBy) {
        this.modiBy = modiBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_info_title.MODI_TIME
     *
     * @return the value of t_info_title.MODI_TIME
     *
     * @mbggenerated
     */
    public Date getModiTime() {
        return modiTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_info_title.MODI_TIME
     *
     * @param modiTime the value for t_info_title.MODI_TIME
     *
     * @mbggenerated
     */
    public void setModiTime(Date modiTime) {
        this.modiTime = modiTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_info_title.ORG_ID
     *
     * @return the value of t_info_title.ORG_ID
     *
     * @mbggenerated
     */
    public Long getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_info_title.ORG_ID
     *
     * @param orgId the value for t_info_title.ORG_ID
     *
     * @mbggenerated
     */
    public void setOrgId(Long orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_info_title.SORT_NUM
     *
     * @return the value of t_info_title.SORT_NUM
     *
     * @mbggenerated
     */
    public Integer getSortNum() {
        return sortNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_info_title.SORT_NUM
     *
     * @param sortNum the value for t_info_title.SORT_NUM
     *
     * @mbggenerated
     */
    public void setSortNum(Integer sortNum) {
        this.sortNum = sortNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_info_title.STATUS
     *
     * @return the value of t_info_title.STATUS
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_info_title.STATUS
     *
     * @param status the value for t_info_title.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_info_title.CON_TYPE
     *
     * @return the value of t_info_title.CON_TYPE
     *
     * @mbggenerated
     */
    public Integer getConType() {
        return conType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_info_title.CON_TYPE
     *
     * @param conType the value for t_info_title.CON_TYPE
     *
     * @mbggenerated
     */
    public void setConType(Integer conType) {
        this.conType = conType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_info_title.DESCRIPT
     *
     * @return the value of t_info_title.DESCRIPT
     *
     * @mbggenerated
     */
    public String getDescript() {
        return descript;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_info_title.DESCRIPT
     *
     * @param descript the value for t_info_title.DESCRIPT
     *
     * @mbggenerated
     */
    public void setDescript(String descript) {
        this.descript = descript == null ? null : descript.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_info_title.IMAGE
     *
     * @return the value of t_info_title.IMAGE
     *
     * @mbggenerated
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_info_title.IMAGE
     *
     * @param image the value for t_info_title.IMAGE
     *
     * @mbggenerated
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_info_title.THUMBNAIL
     *
     * @return the value of t_info_title.THUMBNAIL
     *
     * @mbggenerated
     */
    public String getThumbnail() {
        return thumbnail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_info_title.THUMBNAIL
     *
     * @param thumbnail the value for t_info_title.THUMBNAIL
     *
     * @mbggenerated
     */
    public void setThumbnail(String thumbnail) {
        this.thumbnail = thumbnail == null ? null : thumbnail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_info_title.INI_STATUS
     *
     * @return the value of t_info_title.INI_STATUS
     *
     * @mbggenerated
     */
    public Integer getIniStatus() {
        return iniStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_info_title.INI_STATUS
     *
     * @param iniStatus the value for t_info_title.INI_STATUS
     *
     * @mbggenerated
     */
    public void setIniStatus(Integer iniStatus) {
        this.iniStatus = iniStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_info_title.KEY_WORDS
     *
     * @return the value of t_info_title.KEY_WORDS
     *
     * @mbggenerated
     */
    public String getKeyWords() {
        return keyWords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_info_title.KEY_WORDS
     *
     * @param keyWords the value for t_info_title.KEY_WORDS
     *
     * @mbggenerated
     */
    public void setKeyWords(String keyWords) {
        this.keyWords = keyWords == null ? null : keyWords.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_info_title.REC_TAGS
     *
     * @return the value of t_info_title.REC_TAGS
     *
     * @mbggenerated
     */
    public String getRecTags() {
        return recTags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_info_title.REC_TAGS
     *
     * @param recTags the value for t_info_title.REC_TAGS
     *
     * @mbggenerated
     */
    public void setRecTags(String recTags) {
        this.recTags = recTags == null ? null : recTags.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_info_title.RELEASE_TIME
     *
     * @return the value of t_info_title.RELEASE_TIME
     *
     * @mbggenerated
     */
    public Date getReleaseTime() {
        return releaseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_info_title.RELEASE_TIME
     *
     * @param releaseTime the value for t_info_title.RELEASE_TIME
     *
     * @mbggenerated
     */
    public void setReleaseTime(Date releaseTime) {
        this.releaseTime = releaseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_info_title.RESOURCES
     *
     * @return the value of t_info_title.RESOURCES
     *
     * @mbggenerated
     */
    public String getResources() {
        return resources;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_info_title.RESOURCES
     *
     * @param resources the value for t_info_title.RESOURCES
     *
     * @mbggenerated
     */
    public void setResources(String resources) {
        this.resources = resources == null ? null : resources.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_info_title.SUBTITLE
     *
     * @return the value of t_info_title.SUBTITLE
     *
     * @mbggenerated
     */
    public String getSubtitle() {
        return subtitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_info_title.SUBTITLE
     *
     * @param subtitle the value for t_info_title.SUBTITLE
     *
     * @mbggenerated
     */
    public void setSubtitle(String subtitle) {
        this.subtitle = subtitle == null ? null : subtitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_info_title.TITLE
     *
     * @return the value of t_info_title.TITLE
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_info_title.TITLE
     *
     * @param title the value for t_info_title.TITLE
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_info_title.REFUSE_CASE
     *
     * @return the value of t_info_title.REFUSE_CASE
     *
     * @mbggenerated
     */
    public String getRefuseCase() {
        return refuseCase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_info_title.REFUSE_CASE
     *
     * @param refuseCase the value for t_info_title.REFUSE_CASE
     *
     * @mbggenerated
     */
    public void setRefuseCase(String refuseCase) {
        this.refuseCase = refuseCase == null ? null : refuseCase.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_info_title.DURATION
     *
     * @return the value of t_info_title.DURATION
     *
     * @mbggenerated
     */
    public String getDuration() {
        return duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_info_title.DURATION
     *
     * @param duration the value for t_info_title.DURATION
     *
     * @mbggenerated
     */
    public void setDuration(String duration) {
        this.duration = duration == null ? null : duration.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_info_title.CHANNEL_ID
     *
     * @return the value of t_info_title.CHANNEL_ID
     *
     * @mbggenerated
     */
    public Long getChannelId() {
        return channelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_info_title.CHANNEL_ID
     *
     * @param channelId the value for t_info_title.CHANNEL_ID
     *
     * @mbggenerated
     */
    public void setChannelId(Long channelId) {
        this.channelId = channelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_info_title.CLASSIFY_ID
     *
     * @return the value of t_info_title.CLASSIFY_ID
     *
     * @mbggenerated
     */
    public Long getClassifyId() {
        return classifyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_info_title.CLASSIFY_ID
     *
     * @param classifyId the value for t_info_title.CLASSIFY_ID
     *
     * @mbggenerated
     */
    public void setClassifyId(Long classifyId) {
        this.classifyId = classifyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_info_title.PRODUCT_ID
     *
     * @return the value of t_info_title.PRODUCT_ID
     *
     * @mbggenerated
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_info_title.PRODUCT_ID
     *
     * @param productId the value for t_info_title.PRODUCT_ID
     *
     * @mbggenerated
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_info_title.IS_RECOMMEND
     *
     * @return the value of t_info_title.IS_RECOMMEND
     *
     * @mbggenerated
     */
    public Integer getIsRecommend() {
        return isRecommend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_info_title.IS_RECOMMEND
     *
     * @param isRecommend the value for t_info_title.IS_RECOMMEND
     *
     * @mbggenerated
     */
    public void setIsRecommend(Integer isRecommend) {
        this.isRecommend = isRecommend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_info_title.AUDITOR
     *
     * @return the value of t_info_title.AUDITOR
     *
     * @mbggenerated
     */
    public Long getAuditor() {
        return auditor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_info_title.AUDITOR
     *
     * @param auditor the value for t_info_title.AUDITOR
     *
     * @mbggenerated
     */
    public void setAuditor(Long auditor) {
        this.auditor = auditor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_info_title.AUDIT_TIME
     *
     * @return the value of t_info_title.AUDIT_TIME
     *
     * @mbggenerated
     */
    public Date getAuditTime() {
        return auditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_info_title.AUDIT_TIME
     *
     * @param auditTime the value for t_info_title.AUDIT_TIME
     *
     * @mbggenerated
     */
    public void setAuditTime(Date auditTime) {
        this.auditTime = auditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_info_title.IS_MANAGE
     *
     * @return the value of t_info_title.IS_MANAGE
     *
     * @mbggenerated
     */
    public Integer getIsManage() {
        return isManage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_info_title.IS_MANAGE
     *
     * @param isManage the value for t_info_title.IS_MANAGE
     *
     * @mbggenerated
     */
    public void setIsManage(Integer isManage) {
        this.isManage = isManage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_info_title.CONTENT
     *
     * @return the value of t_info_title.CONTENT
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_info_title.CONTENT
     *
     * @param content the value for t_info_title.CONTENT
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_info_title
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", nId=").append(nId);
        sb.append(", str0=").append(str0);
        sb.append(", str1=").append(str1);
        sb.append(", compId=").append(compId);
        sb.append(", createBy=").append(createBy);
        sb.append(", createTime=").append(createTime);
        sb.append(", modiBy=").append(modiBy);
        sb.append(", modiTime=").append(modiTime);
        sb.append(", orgId=").append(orgId);
        sb.append(", sortNum=").append(sortNum);
        sb.append(", status=").append(status);
        sb.append(", conType=").append(conType);
        sb.append(", descript=").append(descript);
        sb.append(", image=").append(image);
        sb.append(", thumbnail=").append(thumbnail);
        sb.append(", iniStatus=").append(iniStatus);
        sb.append(", keyWords=").append(keyWords);
        sb.append(", recTags=").append(recTags);
        sb.append(", releaseTime=").append(releaseTime);
        sb.append(", resources=").append(resources);
        sb.append(", subtitle=").append(subtitle);
        sb.append(", title=").append(title);
        sb.append(", refuseCase=").append(refuseCase);
        sb.append(", duration=").append(duration);
        sb.append(", channelId=").append(channelId);
        sb.append(", classifyId=").append(classifyId);
        sb.append(", productId=").append(productId);
        sb.append(", isRecommend=").append(isRecommend);
        sb.append(", auditor=").append(auditor);
        sb.append(", auditTime=").append(auditTime);
        sb.append(", isManage=").append(isManage);
        sb.append(", content=").append(content);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}