package top.lover.hyperlink.entity;

import java.io.Serializable;
import java.util.Date;

public class TInfoReview implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_info_review.N_ID
     *
     * @mbggenerated
     */
    private Long nId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_info_review.STR0
     *
     * @mbggenerated
     */
    private String str0;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_info_review.STR1
     *
     * @mbggenerated
     */
    private String str1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_info_review.COMP_ID
     *
     * @mbggenerated
     */
    private Long compId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_info_review.CREATE_BY
     *
     * @mbggenerated
     */
    private Long createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_info_review.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_info_review.MODI_BY
     *
     * @mbggenerated
     */
    private Long modiBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_info_review.MODI_TIME
     *
     * @mbggenerated
     */
    private Date modiTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_info_review.ORG_ID
     *
     * @mbggenerated
     */
    private Long orgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_info_review.SORT_NUM
     *
     * @mbggenerated
     */
    private Integer sortNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_info_review.STATUS
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_info_review.AUDITOR
     *
     * @mbggenerated
     */
    private Long auditor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_info_review.AUDIT_TIME
     *
     * @mbggenerated
     */
    private Date auditTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_info_review.CONTENT
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_info_review.REFUSE_CASE
     *
     * @mbggenerated
     */
    private String refuseCase;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_info_review.REVIEW_STATUS
     *
     * @mbggenerated
     */
    private Integer reviewStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_info_review.TITLE_ID
     *
     * @mbggenerated
     */
    private Long titleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_info_review.TYPE
     *
     * @mbggenerated
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_info_review.USER_ID
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_info_review.USER_NAME
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_info_review.REVIEW_ID
     *
     * @mbggenerated
     */
    private Long reviewId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_info_review.PRODUCT_ID
     *
     * @mbggenerated
     */
    private Long productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_info_review
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_info_review.N_ID
     *
     * @return the value of t_info_review.N_ID
     *
     * @mbggenerated
     */
    public Long getnId() {
        return nId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_info_review.N_ID
     *
     * @param nId the value for t_info_review.N_ID
     *
     * @mbggenerated
     */
    public void setnId(Long nId) {
        this.nId = nId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_info_review.STR0
     *
     * @return the value of t_info_review.STR0
     *
     * @mbggenerated
     */
    public String getStr0() {
        return str0;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_info_review.STR0
     *
     * @param str0 the value for t_info_review.STR0
     *
     * @mbggenerated
     */
    public void setStr0(String str0) {
        this.str0 = str0 == null ? null : str0.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_info_review.STR1
     *
     * @return the value of t_info_review.STR1
     *
     * @mbggenerated
     */
    public String getStr1() {
        return str1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_info_review.STR1
     *
     * @param str1 the value for t_info_review.STR1
     *
     * @mbggenerated
     */
    public void setStr1(String str1) {
        this.str1 = str1 == null ? null : str1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_info_review.COMP_ID
     *
     * @return the value of t_info_review.COMP_ID
     *
     * @mbggenerated
     */
    public Long getCompId() {
        return compId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_info_review.COMP_ID
     *
     * @param compId the value for t_info_review.COMP_ID
     *
     * @mbggenerated
     */
    public void setCompId(Long compId) {
        this.compId = compId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_info_review.CREATE_BY
     *
     * @return the value of t_info_review.CREATE_BY
     *
     * @mbggenerated
     */
    public Long getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_info_review.CREATE_BY
     *
     * @param createBy the value for t_info_review.CREATE_BY
     *
     * @mbggenerated
     */
    public void setCreateBy(Long createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_info_review.CREATE_TIME
     *
     * @return the value of t_info_review.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_info_review.CREATE_TIME
     *
     * @param createTime the value for t_info_review.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_info_review.MODI_BY
     *
     * @return the value of t_info_review.MODI_BY
     *
     * @mbggenerated
     */
    public Long getModiBy() {
        return modiBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_info_review.MODI_BY
     *
     * @param modiBy the value for t_info_review.MODI_BY
     *
     * @mbggenerated
     */
    public void setModiBy(Long modiBy) {
        this.modiBy = modiBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_info_review.MODI_TIME
     *
     * @return the value of t_info_review.MODI_TIME
     *
     * @mbggenerated
     */
    public Date getModiTime() {
        return modiTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_info_review.MODI_TIME
     *
     * @param modiTime the value for t_info_review.MODI_TIME
     *
     * @mbggenerated
     */
    public void setModiTime(Date modiTime) {
        this.modiTime = modiTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_info_review.ORG_ID
     *
     * @return the value of t_info_review.ORG_ID
     *
     * @mbggenerated
     */
    public Long getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_info_review.ORG_ID
     *
     * @param orgId the value for t_info_review.ORG_ID
     *
     * @mbggenerated
     */
    public void setOrgId(Long orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_info_review.SORT_NUM
     *
     * @return the value of t_info_review.SORT_NUM
     *
     * @mbggenerated
     */
    public Integer getSortNum() {
        return sortNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_info_review.SORT_NUM
     *
     * @param sortNum the value for t_info_review.SORT_NUM
     *
     * @mbggenerated
     */
    public void setSortNum(Integer sortNum) {
        this.sortNum = sortNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_info_review.STATUS
     *
     * @return the value of t_info_review.STATUS
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_info_review.STATUS
     *
     * @param status the value for t_info_review.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_info_review.AUDITOR
     *
     * @return the value of t_info_review.AUDITOR
     *
     * @mbggenerated
     */
    public Long getAuditor() {
        return auditor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_info_review.AUDITOR
     *
     * @param auditor the value for t_info_review.AUDITOR
     *
     * @mbggenerated
     */
    public void setAuditor(Long auditor) {
        this.auditor = auditor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_info_review.AUDIT_TIME
     *
     * @return the value of t_info_review.AUDIT_TIME
     *
     * @mbggenerated
     */
    public Date getAuditTime() {
        return auditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_info_review.AUDIT_TIME
     *
     * @param auditTime the value for t_info_review.AUDIT_TIME
     *
     * @mbggenerated
     */
    public void setAuditTime(Date auditTime) {
        this.auditTime = auditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_info_review.CONTENT
     *
     * @return the value of t_info_review.CONTENT
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_info_review.CONTENT
     *
     * @param content the value for t_info_review.CONTENT
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_info_review.REFUSE_CASE
     *
     * @return the value of t_info_review.REFUSE_CASE
     *
     * @mbggenerated
     */
    public String getRefuseCase() {
        return refuseCase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_info_review.REFUSE_CASE
     *
     * @param refuseCase the value for t_info_review.REFUSE_CASE
     *
     * @mbggenerated
     */
    public void setRefuseCase(String refuseCase) {
        this.refuseCase = refuseCase == null ? null : refuseCase.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_info_review.REVIEW_STATUS
     *
     * @return the value of t_info_review.REVIEW_STATUS
     *
     * @mbggenerated
     */
    public Integer getReviewStatus() {
        return reviewStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_info_review.REVIEW_STATUS
     *
     * @param reviewStatus the value for t_info_review.REVIEW_STATUS
     *
     * @mbggenerated
     */
    public void setReviewStatus(Integer reviewStatus) {
        this.reviewStatus = reviewStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_info_review.TITLE_ID
     *
     * @return the value of t_info_review.TITLE_ID
     *
     * @mbggenerated
     */
    public Long getTitleId() {
        return titleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_info_review.TITLE_ID
     *
     * @param titleId the value for t_info_review.TITLE_ID
     *
     * @mbggenerated
     */
    public void setTitleId(Long titleId) {
        this.titleId = titleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_info_review.TYPE
     *
     * @return the value of t_info_review.TYPE
     *
     * @mbggenerated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_info_review.TYPE
     *
     * @param type the value for t_info_review.TYPE
     *
     * @mbggenerated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_info_review.USER_ID
     *
     * @return the value of t_info_review.USER_ID
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_info_review.USER_ID
     *
     * @param userId the value for t_info_review.USER_ID
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_info_review.USER_NAME
     *
     * @return the value of t_info_review.USER_NAME
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_info_review.USER_NAME
     *
     * @param userName the value for t_info_review.USER_NAME
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_info_review.REVIEW_ID
     *
     * @return the value of t_info_review.REVIEW_ID
     *
     * @mbggenerated
     */
    public Long getReviewId() {
        return reviewId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_info_review.REVIEW_ID
     *
     * @param reviewId the value for t_info_review.REVIEW_ID
     *
     * @mbggenerated
     */
    public void setReviewId(Long reviewId) {
        this.reviewId = reviewId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_info_review.PRODUCT_ID
     *
     * @return the value of t_info_review.PRODUCT_ID
     *
     * @mbggenerated
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_info_review.PRODUCT_ID
     *
     * @param productId the value for t_info_review.PRODUCT_ID
     *
     * @mbggenerated
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_info_review
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", nId=").append(nId);
        sb.append(", str0=").append(str0);
        sb.append(", str1=").append(str1);
        sb.append(", compId=").append(compId);
        sb.append(", createBy=").append(createBy);
        sb.append(", createTime=").append(createTime);
        sb.append(", modiBy=").append(modiBy);
        sb.append(", modiTime=").append(modiTime);
        sb.append(", orgId=").append(orgId);
        sb.append(", sortNum=").append(sortNum);
        sb.append(", status=").append(status);
        sb.append(", auditor=").append(auditor);
        sb.append(", auditTime=").append(auditTime);
        sb.append(", content=").append(content);
        sb.append(", refuseCase=").append(refuseCase);
        sb.append(", reviewStatus=").append(reviewStatus);
        sb.append(", titleId=").append(titleId);
        sb.append(", type=").append(type);
        sb.append(", userId=").append(userId);
        sb.append(", userName=").append(userName);
        sb.append(", reviewId=").append(reviewId);
        sb.append(", productId=").append(productId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}