package top.lover.hyperlink.dao;

import java.util.List;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import org.apache.ibatis.annotations.Mapper;
import top.lover.hyperlink.entity.CsActivationStatistics;

@Mapper
public interface CsActivationStatisticsMapper extends BaseMapper<CsActivationStatistics> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_activation_statistics
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long nId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_activation_statistics
     *
     * @mbggenerated
     */
    int insert(CsActivationStatistics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_activation_statistics
     *
     * @mbggenerated
     */
    CsActivationStatistics selectByPrimaryKey(Long nId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_activation_statistics
     *
     * @mbggenerated
     */
    List<CsActivationStatistics> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_activation_statistics
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CsActivationStatistics record);
}