package top.lover.hyperlink.dao;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import org.apache.ibatis.annotations.Mapper;
import top.lover.hyperlink.entity.CsAccessRateSet;

import java.util.List;

@Mapper
public interface CsAccessRateSetMapper extends BaseMapper<CsAccessRateSet> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_access_rate_set
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long nId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_access_rate_set
     *
     * @mbggenerated
     */
    int insert(CsAccessRateSet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_access_rate_set
     *
     * @mbggenerated
     */
    CsAccessRateSet selectByPrimaryKey(Long nId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_access_rate_set
     *
     * @mbggenerated
     */
    List<CsAccessRateSet> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_access_rate_set
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CsAccessRateSet record);
}