package top.lover.hyperlink.dao;

import java.util.List;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import org.apache.ibatis.annotations.Mapper;
import top.lover.hyperlink.entity.CsDefaultTouchTime;

@Mapper
public interface CsDefaultTouchTimeMapper extends BaseMapper<CsDefaultTouchTime> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_default_touch_time
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long nId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_default_touch_time
     *
     * @mbggenerated
     */
    int insert(CsDefaultTouchTime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_default_touch_time
     *
     * @mbggenerated
     */
    CsDefaultTouchTime selectByPrimaryKey(Long nId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_default_touch_time
     *
     * @mbggenerated
     */
    List<CsDefaultTouchTime> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_default_touch_time
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CsDefaultTouchTime record);
}