package top.lover.hyperlink.dao;

import java.util.List;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import org.apache.ibatis.annotations.Mapper;
import top.lover.hyperlink.entity.CsDownloadStatistics;

@Mapper
public interface CsDownloadStatisticsMapper extends BaseMapper<CsDownloadStatistics> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_download_statistics
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long nId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_download_statistics
     *
     * @mbggenerated
     */
    int insert(CsDownloadStatistics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_download_statistics
     *
     * @mbggenerated
     */
    CsDownloadStatistics selectByPrimaryKey(Long nId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_download_statistics
     *
     * @mbggenerated
     */
    List<CsDownloadStatistics> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_download_statistics
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CsDownloadStatistics record);
}