package top.lover.hyperlink.dao;

import java.util.List;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import org.apache.ibatis.annotations.Mapper;
import top.lover.hyperlink.entity.CsOverviewRecords;

@Mapper
public interface CsOverviewRecordsMapper extends BaseMapper<CsOverviewRecords> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_overview_records
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long nId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_overview_records
     *
     * @mbggenerated
     */
    int insert(CsOverviewRecords record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_overview_records
     *
     * @mbggenerated
     */
    CsOverviewRecords selectByPrimaryKey(Long nId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_overview_records
     *
     * @mbggenerated
     */
    List<CsOverviewRecords> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_overview_records
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CsOverviewRecords record);
}