package top.lover.hyperlink.dao;

import java.util.List;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import org.apache.ibatis.annotations.Mapper;
import top.lover.hyperlink.entity.CsPushRecord;

@Mapper
public interface CsPushRecordMapper extends BaseMapper<CsPushRecord> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_push_record
     *
     * @mbggenerated
     */
    int insert(CsPushRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_push_record
     *
     * @mbggenerated
     */
    List<CsPushRecord> selectAll();
}