package top.lover.hyperlink.dao;

import java.util.List;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import org.apache.ibatis.annotations.Mapper;
import top.lover.hyperlink.entity.CsPushSet;

@Mapper
public interface CsPushSetMapper extends BaseMapper<CsPushSet> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_push_set
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long nId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_push_set
     *
     * @mbggenerated
     */
    int insert(CsPushSet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_push_set
     *
     * @mbggenerated
     */
    CsPushSet selectByPrimaryKey(Long nId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_push_set
     *
     * @mbggenerated
     */
    List<CsPushSet> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_push_set
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CsPushSet record);
}