package top.lover.hyperlink.dao;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import org.apache.ibatis.annotations.Mapper;
import top.lover.hyperlink.entity.CsPushSetRelev;

import java.util.List;

@Mapper
public interface CsPushSetRelevMapper extends BaseMapper<CsPushSetRelev> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_push_set_relev
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long nId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_push_set_relev
     *
     * @mbggenerated
     */
    int insert(CsPushSetRelev record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_push_set_relev
     *
     * @mbggenerated
     */
    CsPushSetRelev selectByPrimaryKey(Long nId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_push_set_relev
     *
     * @mbggenerated
     */
    List<CsPushSetRelev> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_push_set_relev
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CsPushSetRelev record);
}