package top.lover.hyperlink.dao;

import java.util.List;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import org.apache.ibatis.annotations.Mapper;
import top.lover.hyperlink.entity.CsRetainDataStatistics;

@Mapper
public interface CsRetainDataStatisticsMapper extends BaseMapper<CsRetainDataStatistics> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_retain_data_statistics
     *
     * @mbggenerated
     */
    int insert(CsRetainDataStatistics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_retain_data_statistics
     *
     * @mbggenerated
     */
    List<CsRetainDataStatistics> selectAll();
}