package top.lover.hyperlink.dao;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import org.apache.ibatis.annotations.Mapper;
import top.lover.hyperlink.entity.CsSmsRecord;

import java.util.List;

@Mapper
public interface CsSmsRecordMapper extends BaseMapper<CsSmsRecord> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_sms_record
     *
     * @mbggenerated
     */
    int insert(CsSmsRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_sms_record
     *
     * @mbggenerated
     */
    List<CsSmsRecord> selectAll();
}