package top.lover.hyperlink.dao;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import org.apache.ibatis.annotations.Mapper;
import top.lover.hyperlink.entity.CsSmsSetRelev;

import java.util.List;

@Mapper
public interface CsSmsSetRelevMapper extends BaseMapper<CsSmsSetRelev> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_sms_set_relev
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long nId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_sms_set_relev
     *
     * @mbggenerated
     */
    int insert(CsSmsSetRelev record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_sms_set_relev
     *
     * @mbggenerated
     */
    CsSmsSetRelev selectByPrimaryKey(Long nId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_sms_set_relev
     *
     * @mbggenerated
     */
    List<CsSmsSetRelev> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_sms_set_relev
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CsSmsSetRelev record);
}