package top.lover.hyperlink.dao;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import org.apache.ibatis.annotations.Mapper;
import top.lover.hyperlink.entity.CsSmsSet;

import java.util.List;

@Mapper
public interface CsSmsSetMapper extends BaseMapper<CsSmsSet> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_sms_set
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long nId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_sms_set
     *
     * @mbggenerated
     */
    int insert(CsSmsSet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_sms_set
     *
     * @mbggenerated
     */
    CsSmsSet selectByPrimaryKey(Long nId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_sms_set
     *
     * @mbggenerated
     */
    List<CsSmsSet> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_sms_set
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CsSmsSet record);
}