package top.lover.hyperlink.dao;

import java.util.List;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import org.apache.ibatis.annotations.Mapper;
import top.lover.hyperlink.entity.CsStatusMonitoringStatistics;

@Mapper
public interface CsStatusMonitoringStatisticsMapper extends BaseMapper<CsStatusMonitoringStatistics> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_status_monitoring_statistics
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long nId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_status_monitoring_statistics
     *
     * @mbggenerated
     */
    int insert(CsStatusMonitoringStatistics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_status_monitoring_statistics
     *
     * @mbggenerated
     */
    CsStatusMonitoringStatistics selectByPrimaryKey(Long nId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_status_monitoring_statistics
     *
     * @mbggenerated
     */
    List<CsStatusMonitoringStatistics> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_status_monitoring_statistics
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CsStatusMonitoringStatistics record);
}