package top.lover.hyperlink.dao;

import java.util.List;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import org.apache.ibatis.annotations.Mapper;
import top.lover.hyperlink.entity.CsTouchupStatistics;

@Mapper
public interface CsTouchupStatisticsMapper extends BaseMapper<CsTouchupStatistics> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_touchup_statistics
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long nId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_touchup_statistics
     *
     * @mbggenerated
     */
    int insert(CsTouchupStatistics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_touchup_statistics
     *
     * @mbggenerated
     */
    CsTouchupStatistics selectByPrimaryKey(Long nId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_touchup_statistics
     *
     * @mbggenerated
     */
    List<CsTouchupStatistics> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_touchup_statistics
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CsTouchupStatistics record);
}