package top.lover.hyperlink.dao;

import java.util.List;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import org.apache.ibatis.annotations.Mapper;
import top.lover.hyperlink.entity.CsUsersStatistics;

@Mapper
public interface CsUsersStatisticsMapper extends BaseMapper<CsUsersStatistics> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_users_statistics
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long nId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_users_statistics
     *
     * @mbggenerated
     */
    int insert(CsUsersStatistics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_users_statistics
     *
     * @mbggenerated
     */
    CsUsersStatistics selectByPrimaryKey(Long nId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_users_statistics
     *
     * @mbggenerated
     */
    List<CsUsersStatistics> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_users_statistics
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CsUsersStatistics record);
}