package top.lover.hyperlink.dao;

import java.util.List;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import org.apache.ibatis.annotations.Mapper;
import top.lover.hyperlink.entity.CsVisitStatistics;

@Mapper
public interface CsVisitStatisticsMapper extends BaseMapper<CsVisitStatistics> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_visit_statistics
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long nId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_visit_statistics
     *
     * @mbggenerated
     */
    int insert(CsVisitStatistics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_visit_statistics
     *
     * @mbggenerated
     */
    CsVisitStatistics selectByPrimaryKey(Long nId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_visit_statistics
     *
     * @mbggenerated
     */
    List<CsVisitStatistics> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_visit_statistics
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CsVisitStatistics record);
}