package top.lover.hyperlink.dao;

import java.util.List;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import org.apache.ibatis.annotations.Mapper;
import top.lover.hyperlink.entity.TCityInfo;

@Mapper
public interface TCityInfoMapper extends BaseMapper<TCityInfo> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_city_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_city_info
     *
     * @mbggenerated
     */
    int insert(TCityInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_city_info
     *
     * @mbggenerated
     */
    TCityInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_city_info
     *
     * @mbggenerated
     */
    List<TCityInfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_city_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TCityInfo record);
}