package top.lover.hyperlink.dao;

import java.util.List;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import org.apache.ibatis.annotations.Mapper;
import top.lover.hyperlink.entity.TInfoReview;

@Mapper
public interface TInfoReviewMapper extends BaseMapper<TInfoReview> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_info_review
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long nId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_info_review
     *
     * @mbggenerated
     */
    int insert(TInfoReview record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_info_review
     *
     * @mbggenerated
     */
    TInfoReview selectByPrimaryKey(Long nId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_info_review
     *
     * @mbggenerated
     */
    List<TInfoReview> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_info_review
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TInfoReview record);
}