package top.lover.hyperlink.dao;

import java.util.List;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import org.apache.ibatis.annotations.Mapper;
import top.lover.hyperlink.entity.TInfoTitle;

@Mapper
public interface TInfoTitleMapper extends BaseMapper<TInfoTitle> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_info_title
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long nId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_info_title
     *
     * @mbggenerated
     */
    int insert(TInfoTitle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_info_title
     *
     * @mbggenerated
     */
    TInfoTitle selectByPrimaryKey(Long nId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_info_title
     *
     * @mbggenerated
     */
    List<TInfoTitle> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_info_title
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TInfoTitle record);
}